# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSplitter, QStatusBar,
    QTabWidget, QToolBar, QVBoxLayout, QWidget)

from genx.gui_qt.data_grid_panel import DataGridPanel
from genx.gui_qt.datalist import DataListControl
from genx.gui_qt.parametergrid import ParameterGrid
from genx.gui_qt.plotpanel import (DataPlotPanel, ErrorPlotPanel, FomScanPlotPanel, ParsPlotPanel)
from genx.gui_qt.script_editor import GenxScriptEditor
from . import genx_resources_rc

class Ui_GenxMainWindowUI(object):
    def setupUi(self, GenxMainWindowUI):
        if not GenxMainWindowUI.objectName():
            GenxMainWindowUI.setObjectName(u"GenxMainWindowUI")
        GenxMainWindowUI.resize(1180, 870)
        icon = QIcon()
        icon.addFile(u":/main_gui/genx.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/main_gui/genx.ico", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        GenxMainWindowUI.setWindowIcon(icon)
        self.actionNewModel = QAction(GenxMainWindowUI)
        self.actionNewModel.setObjectName(u"actionNewModel")
        icon1 = QIcon()
        icon1.addFile(u":/main_gui/new.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/main_gui/new.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionNewModel.setIcon(icon1)
        self.actionNewFromFile = QAction(GenxMainWindowUI)
        self.actionNewFromFile.setObjectName(u"actionNewFromFile")
        icon2 = QIcon()
        icon2.addFile(u":/main_gui/new_from_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/main_gui/new_from_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionNewFromFile.setIcon(icon2)
        self.actionOpenModel = QAction(GenxMainWindowUI)
        self.actionOpenModel.setObjectName(u"actionOpenModel")
        icon3 = QIcon()
        icon3.addFile(u":/main_gui/open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/main_gui/open.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionOpenModel.setIcon(icon3)
        self.actionSaveModel = QAction(GenxMainWindowUI)
        self.actionSaveModel.setObjectName(u"actionSaveModel")
        icon4 = QIcon()
        icon4.addFile(u":/main_gui/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u":/main_gui/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionSaveModel.setIcon(icon4)
        self.actionSaveModelAs = QAction(GenxMainWindowUI)
        self.actionSaveModelAs.setObjectName(u"actionSaveModelAs")
        self.actionQuit = QAction(GenxMainWindowUI)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionBatchDialog = QAction(GenxMainWindowUI)
        self.actionBatchDialog.setObjectName(u"actionBatchDialog")
        self.actionImportData = QAction(GenxMainWindowUI)
        self.actionImportData.setObjectName(u"actionImportData")
        self.actionImportTable = QAction(GenxMainWindowUI)
        self.actionImportTable.setObjectName(u"actionImportTable")
        self.actionImportScript = QAction(GenxMainWindowUI)
        self.actionImportScript.setObjectName(u"actionImportScript")
        self.actionExportOrso = QAction(GenxMainWindowUI)
        self.actionExportOrso.setObjectName(u"actionExportOrso")
        self.actionExportData = QAction(GenxMainWindowUI)
        self.actionExportData.setObjectName(u"actionExportData")
        self.actionExportTable = QAction(GenxMainWindowUI)
        self.actionExportTable.setObjectName(u"actionExportTable")
        self.actionExportScript = QAction(GenxMainWindowUI)
        self.actionExportScript.setObjectName(u"actionExportScript")
        self.actionPublishPlot = QAction(GenxMainWindowUI)
        self.actionPublishPlot.setObjectName(u"actionPublishPlot")
        self.actionPrintPlot = QAction(GenxMainWindowUI)
        self.actionPrintPlot.setObjectName(u"actionPrintPlot")
        self.actionPrintGrid = QAction(GenxMainWindowUI)
        self.actionPrintGrid.setObjectName(u"actionPrintGrid")
        self.actionPrintScript = QAction(GenxMainWindowUI)
        self.actionPrintScript.setObjectName(u"actionPrintScript")
        self.actionUndo = QAction(GenxMainWindowUI)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(GenxMainWindowUI)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionHistory = QAction(GenxMainWindowUI)
        self.actionHistory.setObjectName(u"actionHistory")
        self.actionCopyGraph = QAction(GenxMainWindowUI)
        self.actionCopyGraph.setObjectName(u"actionCopyGraph")
        self.actionCopySimulation = QAction(GenxMainWindowUI)
        self.actionCopySimulation.setObjectName(u"actionCopySimulation")
        self.actionCopyTable = QAction(GenxMainWindowUI)
        self.actionCopyTable.setObjectName(u"actionCopyTable")
        self.actionFindReplace = QAction(GenxMainWindowUI)
        self.actionFindReplace.setObjectName(u"actionFindReplace")
        self.actionOpenInEditor = QAction(GenxMainWindowUI)
        self.actionOpenInEditor.setObjectName(u"actionOpenInEditor")
        self.actionNewDataSet = QAction(GenxMainWindowUI)
        self.actionNewDataSet.setObjectName(u"actionNewDataSet")
        self.actionDeleteDataSet = QAction(GenxMainWindowUI)
        self.actionDeleteDataSet.setObjectName(u"actionDeleteDataSet")
        self.actionLowerData = QAction(GenxMainWindowUI)
        self.actionLowerData.setObjectName(u"actionLowerData")
        self.actionRaiseData = QAction(GenxMainWindowUI)
        self.actionRaiseData.setObjectName(u"actionRaiseData")
        self.actionToggleShow = QAction(GenxMainWindowUI)
        self.actionToggleShow.setObjectName(u"actionToggleShow")
        self.actionToggleUse = QAction(GenxMainWindowUI)
        self.actionToggleUse.setObjectName(u"actionToggleUse")
        self.actionToggleError = QAction(GenxMainWindowUI)
        self.actionToggleError.setObjectName(u"actionToggleError")
        self.actionCalculations = QAction(GenxMainWindowUI)
        self.actionCalculations.setObjectName(u"actionCalculations")
        self.actionValueAsSlider = QAction(GenxMainWindowUI)
        self.actionValueAsSlider.setObjectName(u"actionValueAsSlider")
        self.actionValueAsSlider.setCheckable(True)
        self.actionPlotMarkers = QAction(GenxMainWindowUI)
        self.actionPlotMarkers.setObjectName(u"actionPlotMarkers")
        self.actionUseToggleShow = QAction(GenxMainWindowUI)
        self.actionUseToggleShow.setObjectName(u"actionUseToggleShow")
        self.actionUseToggleShow.setCheckable(True)
        self.actionColorNone = QAction(GenxMainWindowUI)
        self.actionColorNone.setObjectName(u"actionColorNone")
        self.actionColorNone.setCheckable(True)
        self.actionColorCycle1 = QAction(GenxMainWindowUI)
        self.actionColorCycle1.setObjectName(u"actionColorCycle1")
        self.actionColorCycle1.setCheckable(True)
        self.actionColorCycle2 = QAction(GenxMainWindowUI)
        self.actionColorCycle2.setObjectName(u"actionColorCycle2")
        self.actionColorCycle2.setCheckable(True)
        self.actionYScaleLog = QAction(GenxMainWindowUI)
        self.actionYScaleLog.setObjectName(u"actionYScaleLog")
        self.actionYScaleLog.setCheckable(True)
        self.actionYScaleLin = QAction(GenxMainWindowUI)
        self.actionYScaleLin.setObjectName(u"actionYScaleLin")
        self.actionYScaleLin.setCheckable(True)
        self.actionXScaleLog = QAction(GenxMainWindowUI)
        self.actionXScaleLog.setObjectName(u"actionXScaleLog")
        self.actionXScaleLog.setCheckable(True)
        self.actionXScaleLin = QAction(GenxMainWindowUI)
        self.actionXScaleLin.setObjectName(u"actionXScaleLin")
        self.actionXScaleLin.setCheckable(True)
        self.actionSimulateAutomatically = QAction(GenxMainWindowUI)
        self.actionSimulateAutomatically.setObjectName(u"actionSimulateAutomatically")
        self.actionSimulateAutomatically.setCheckable(True)
        self.actionSimulate = QAction(GenxMainWindowUI)
        self.actionSimulate.setObjectName(u"actionSimulate")
        icon5 = QIcon()
        icon5.addFile(u":/main_gui/simulate.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon5.addFile(u":/main_gui/simulate.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionSimulate.setIcon(icon5)
        self.actionEvaluate = QAction(GenxMainWindowUI)
        self.actionEvaluate.setObjectName(u"actionEvaluate")
        self.actionUseCuda = QAction(GenxMainWindowUI)
        self.actionUseCuda.setObjectName(u"actionUseCuda")
        self.actionUseCuda.setCheckable(True)
        self.actionStartFit = QAction(GenxMainWindowUI)
        self.actionStartFit.setObjectName(u"actionStartFit")
        icon6 = QIcon()
        icon6.addFile(u":/main_gui/start_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon6.addFile(u":/main_gui/start_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionStartFit.setIcon(icon6)
        self.actionStopFit = QAction(GenxMainWindowUI)
        self.actionStopFit.setObjectName(u"actionStopFit")
        icon7 = QIcon()
        icon7.addFile(u":/main_gui/stop_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon7.addFile(u":/main_gui/stop_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionStopFit.setIcon(icon7)
        self.actionResumeFit = QAction(GenxMainWindowUI)
        self.actionResumeFit.setObjectName(u"actionResumeFit")
        icon8 = QIcon()
        icon8.addFile(u":/main_gui/restart_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon8.addFile(u":/main_gui/restart_fit.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionResumeFit.setIcon(icon8)
        self.actionAnalyzeFit = QAction(GenxMainWindowUI)
        self.actionAnalyzeFit.setObjectName(u"actionAnalyzeFit")
        self.actionCalcErrorBars = QAction(GenxMainWindowUI)
        self.actionCalcErrorBars.setObjectName(u"actionCalcErrorBars")
        icon9 = QIcon()
        icon9.addFile(u":/main_gui/calc_error_bar.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon9.addFile(u":/main_gui/calc_error_bar.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionCalcErrorBars.setIcon(icon9)
        self.actionErrorStatistics = QAction(GenxMainWindowUI)
        self.actionErrorStatistics.setObjectName(u"actionErrorStatistics")
        icon10 = QIcon()
        icon10.addFile(u":/main_gui/par_proj.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon10.addFile(u":/main_gui/par_proj.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionErrorStatistics.setIcon(icon10)
        self.actionOptimizer = QAction(GenxMainWindowUI)
        self.actionOptimizer.setObjectName(u"actionOptimizer")
        self.actionDataLoader = QAction(GenxMainWindowUI)
        self.actionDataLoader.setObjectName(u"actionDataLoader")
        self.actionImportSettings = QAction(GenxMainWindowUI)
        self.actionImportSettings.setObjectName(u"actionImportSettings")
        self.actionStartupProfile = QAction(GenxMainWindowUI)
        self.actionStartupProfile.setObjectName(u"actionStartupProfile")
        self.actionSelectExternalEditor = QAction(GenxMainWindowUI)
        self.actionSelectExternalEditor.setObjectName(u"actionSelectExternalEditor")
        self.actionModelsHelp = QAction(GenxMainWindowUI)
        self.actionModelsHelp.setObjectName(u"actionModelsHelp")
        self.actionFomHelp = QAction(GenxMainWindowUI)
        self.actionFomHelp.setObjectName(u"actionFomHelp")
        self.actionPluginsHelp = QAction(GenxMainWindowUI)
        self.actionPluginsHelp.setObjectName(u"actionPluginsHelp")
        self.actionDataLoadersHelp = QAction(GenxMainWindowUI)
        self.actionDataLoadersHelp.setObjectName(u"actionDataLoadersHelp")
        self.actionOpenExamples = QAction(GenxMainWindowUI)
        self.actionOpenExamples.setObjectName(u"actionOpenExamples")
        self.actionOpenManual = QAction(GenxMainWindowUI)
        self.actionOpenManual.setObjectName(u"actionOpenManual")
        self.actionOpenHomepage = QAction(GenxMainWindowUI)
        self.actionOpenHomepage.setObjectName(u"actionOpenHomepage")
        self.actionAbout = QAction(GenxMainWindowUI)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCollectDebugInfo = QAction(GenxMainWindowUI)
        self.actionCollectDebugInfo.setObjectName(u"actionCollectDebugInfo")
        self.centralwidget = QWidget(GenxMainWindowUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralLayout = QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName(u"centralLayout")
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.mainSplitter = QSplitter(self.centralwidget)
        self.mainSplitter.setObjectName(u"mainSplitter")
        self.mainSplitter.setFrameShape(QFrame.StyledPanel)
        self.mainSplitter.setFrameShadow(QFrame.Sunken)
        self.mainSplitter.setOrientation(Qt.Horizontal)
        self.leftSplitter = QSplitter(self.mainSplitter)
        self.leftSplitter.setObjectName(u"leftSplitter")
        self.leftSplitter.setOrientation(Qt.Vertical)
        self.leftTabWidget = QTabWidget(self.leftSplitter)
        self.leftTabWidget.setObjectName(u"leftTabWidget")
        self.tabData = QWidget()
        self.tabData.setObjectName(u"tabData")
        self.dataTabLayout = QVBoxLayout(self.tabData)
        self.dataTabLayout.setObjectName(u"dataTabLayout")
        self.dataTabLayout.setContentsMargins(0, 0, 0, 0)
        self.dataListControl = DataListControl(self.tabData)
        self.dataListControl.setObjectName(u"dataListControl")

        self.dataTabLayout.addWidget(self.dataListControl)

        self.leftTabWidget.addTab(self.tabData, "")
        self.tabView = QWidget()
        self.tabView.setObjectName(u"tabView")
        self.viewTabLayout = QVBoxLayout(self.tabView)
        self.viewTabLayout.setObjectName(u"viewTabLayout")
        self.viewTabLayout.setContentsMargins(0, 0, 0, 0)
        self.dataGridPanel = DataGridPanel(self.tabView)
        self.dataGridPanel.setObjectName(u"dataGridPanel")

        self.viewTabLayout.addWidget(self.dataGridPanel)

        self.leftTabWidget.addTab(self.tabView, "")
        self.leftSplitter.addWidget(self.leftTabWidget)
        self.leftPluginTabFrame = QFrame(self.leftSplitter)
        self.leftPluginTabFrame.setObjectName(u"leftPluginTabFrame")
        self.leftPluginTabFrame.setFrameShape(QFrame.StyledPanel)
        self.leftPluginTabFrame.setFrameShadow(QFrame.Sunken)
        self.leftPluginTabFrameLayout = QVBoxLayout(self.leftPluginTabFrame)
        self.leftPluginTabFrameLayout.setObjectName(u"leftPluginTabFrameLayout")
        self.leftPluginTabFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.leftPluginTabWidget = QTabWidget(self.leftPluginTabFrame)
        self.leftPluginTabWidget.setObjectName(u"leftPluginTabWidget")
        self.leftPluginTabWidget.setTabPosition(QTabWidget.North)
        self.leftPluginTabWidget.setDocumentMode(True)
        self.leftPluginTabWidget.setMovable(True)

        self.leftPluginTabFrameLayout.addWidget(self.leftPluginTabWidget)

        self.leftSplitter.addWidget(self.leftPluginTabFrame)
        self.mainSplitter.addWidget(self.leftSplitter)
        self.rightSplitter = QSplitter(self.mainSplitter)
        self.rightSplitter.setObjectName(u"rightSplitter")
        self.rightSplitter.setOrientation(Qt.Vertical)
        self.plotSplitter = QSplitter(self.rightSplitter)
        self.plotSplitter.setObjectName(u"plotSplitter")
        self.plotSplitter.setOrientation(Qt.Horizontal)
        self.plotTabFrame = QFrame(self.plotSplitter)
        self.plotTabFrame.setObjectName(u"plotTabFrame")
        self.plotTabFrame.setFrameShape(QFrame.WinPanel)
        self.plotTabFrame.setFrameShadow(QFrame.Raised)
        self.plotTabFrame.setLineWidth(3)
        self.plotTabFrameLayout = QVBoxLayout(self.plotTabFrame)
        self.plotTabFrameLayout.setObjectName(u"plotTabFrameLayout")
        self.plotTabFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.plotTabWidget = QTabWidget(self.plotTabFrame)
        self.plotTabWidget.setObjectName(u"plotTabWidget")
        self.plotTabWidget.setTabPosition(QTabWidget.South)
        self.plotTabWidget.setDocumentMode(True)
        self.plotTabWidget.setMovable(True)
        self.plotTabData = QWidget()
        self.plotTabData.setObjectName(u"plotTabData")
        self.plotDataLayout = QVBoxLayout(self.plotTabData)
        self.plotDataLayout.setObjectName(u"plotDataLayout")
        self.plotDataLayout.setContentsMargins(0, 0, 0, 0)
        self.plotDataPanel = DataPlotPanel(self.plotTabData)
        self.plotDataPanel.setObjectName(u"plotDataPanel")

        self.plotDataLayout.addWidget(self.plotDataPanel)

        self.plotTabWidget.addTab(self.plotTabData, "")
        self.plotTabFom = QWidget()
        self.plotTabFom.setObjectName(u"plotTabFom")
        self.plotFomLayout = QVBoxLayout(self.plotTabFom)
        self.plotFomLayout.setObjectName(u"plotFomLayout")
        self.plotFomLayout.setContentsMargins(0, 0, 0, 0)
        self.plotFomPanel = ErrorPlotPanel(self.plotTabFom)
        self.plotFomPanel.setObjectName(u"plotFomPanel")

        self.plotFomLayout.addWidget(self.plotFomPanel)

        self.plotTabWidget.addTab(self.plotTabFom, "")
        self.plotTabPars = QWidget()
        self.plotTabPars.setObjectName(u"plotTabPars")
        self.plotParsLayout = QVBoxLayout(self.plotTabPars)
        self.plotParsLayout.setObjectName(u"plotParsLayout")
        self.plotParsLayout.setContentsMargins(0, 0, 0, 0)
        self.plotParsPanel = ParsPlotPanel(self.plotTabPars)
        self.plotParsPanel.setObjectName(u"plotParsPanel")

        self.plotParsLayout.addWidget(self.plotParsPanel)

        self.plotTabWidget.addTab(self.plotTabPars, "")
        self.plotTabFomScans = QWidget()
        self.plotTabFomScans.setObjectName(u"plotTabFomScans")
        self.plotFomScansLayout = QVBoxLayout(self.plotTabFomScans)
        self.plotFomScansLayout.setObjectName(u"plotFomScansLayout")
        self.plotFomScansLayout.setContentsMargins(0, 0, 0, 0)
        self.plotFomScansPanel = FomScanPlotPanel(self.plotTabFomScans)
        self.plotFomScansPanel.setObjectName(u"plotFomScansPanel")

        self.plotFomScansLayout.addWidget(self.plotFomScansPanel)

        self.plotTabWidget.addTab(self.plotTabFomScans, "")

        self.plotTabFrameLayout.addWidget(self.plotTabWidget)

        self.plotSplitter.addWidget(self.plotTabFrame)
        self.pluginTabFrame = QFrame(self.plotSplitter)
        self.pluginTabFrame.setObjectName(u"pluginTabFrame")
        self.pluginTabFrame.setFrameShape(QFrame.WinPanel)
        self.pluginTabFrame.setFrameShadow(QFrame.Raised)
        self.pluginTabFrame.setLineWidth(3)
        self.pluginTabFrameLayout = QVBoxLayout(self.pluginTabFrame)
        self.pluginTabFrameLayout.setObjectName(u"pluginTabFrameLayout")
        self.pluginTabFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.pluginTabWidget = QTabWidget(self.pluginTabFrame)
        self.pluginTabWidget.setObjectName(u"pluginTabWidget")
        self.pluginTabWidget.setTabPosition(QTabWidget.South)
        self.pluginTabWidget.setDocumentMode(True)
        self.pluginTabWidget.setMovable(True)
        self.pluginTabEmpty = QWidget()
        self.pluginTabEmpty.setObjectName(u"pluginTabEmpty")
        self.pluginEmptyLayout = QVBoxLayout(self.pluginTabEmpty)
        self.pluginEmptyLayout.setObjectName(u"pluginEmptyLayout")
        self.pluginEmptyLayout.setContentsMargins(0, 0, 0, 0)
        self.pluginTabWidget.addTab(self.pluginTabEmpty, "")

        self.pluginTabFrameLayout.addWidget(self.pluginTabWidget)

        self.plotSplitter.addWidget(self.pluginTabFrame)
        self.rightSplitter.addWidget(self.plotSplitter)
        self.inputTabWidget = QTabWidget(self.rightSplitter)
        self.inputTabWidget.setObjectName(u"inputTabWidget")
        self.inputTabWidget.setTabPosition(QTabWidget.South)
        self.inputTabGrid = QWidget()
        self.inputTabGrid.setObjectName(u"inputTabGrid")
        self.inputGridLayout = QVBoxLayout(self.inputTabGrid)
        self.inputGridLayout.setObjectName(u"inputGridLayout")
        self.inputGridLayout.setContentsMargins(0, 0, 0, 0)
        self.paramterGrid = ParameterGrid(self.inputTabGrid)
        self.paramterGrid.setObjectName(u"paramterGrid")

        self.inputGridLayout.addWidget(self.paramterGrid)

        self.inputTabWidget.addTab(self.inputTabGrid, "")
        self.inputTabScript = QWidget()
        self.inputTabScript.setObjectName(u"inputTabScript")
        self.inputScriptLayout = QVBoxLayout(self.inputTabScript)
        self.inputScriptLayout.setObjectName(u"inputScriptLayout")
        self.inputScriptLayout.setContentsMargins(0, 0, 0, 0)
        self.scriptEditor = GenxScriptEditor(self.inputTabScript)
        self.scriptEditor.setObjectName(u"scriptEditor")

        self.inputScriptLayout.addWidget(self.scriptEditor)

        self.inputTabWidget.addTab(self.inputTabScript, "")
        self.rightSplitter.addWidget(self.inputTabWidget)
        self.mainSplitter.addWidget(self.rightSplitter)

        self.centralLayout.addWidget(self.mainSplitter)

        GenxMainWindowUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(GenxMainWindowUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1180, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuImport = QMenu(self.menuFile)
        self.menuImport.setObjectName(u"menuImport")
        self.menuExport = QMenu(self.menuFile)
        self.menuExport.setObjectName(u"menuExport")
        self.menuPrint = QMenu(self.menuFile)
        self.menuPrint.setObjectName(u"menuPrint")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuData = QMenu(self.menuEdit)
        self.menuData.setObjectName(u"menuData")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuAutoColor = QMenu(self.menuView)
        self.menuAutoColor.setObjectName(u"menuAutoColor")
        self.menuYScale = QMenu(self.menuView)
        self.menuYScale.setObjectName(u"menuYScale")
        self.menuXScale = QMenu(self.menuView)
        self.menuXScale.setObjectName(u"menuXScale")
        self.menuModel = QMenu(self.menubar)
        self.menuModel.setObjectName(u"menuModel")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuPlugins = QMenu(self.menuSettings)
        self.menuPlugins.setObjectName(u"menuPlugins")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        GenxMainWindowUI.setMenuBar(self.menubar)
        self.toolbarMain = QToolBar(GenxMainWindowUI)
        self.toolbarMain.setObjectName(u"toolbarMain")
        GenxMainWindowUI.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolbarMain)
        self.statusbar = QStatusBar(GenxMainWindowUI)
        self.statusbar.setObjectName(u"statusbar")
        GenxMainWindowUI.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNewModel)
        self.menuFile.addAction(self.actionNewFromFile)
        self.menuFile.addAction(self.actionOpenModel)
        self.menuFile.addAction(self.actionSaveModel)
        self.menuFile.addAction(self.actionSaveModelAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBatchDialog)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuPrint.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuImport.addAction(self.actionImportData)
        self.menuImport.addAction(self.actionImportTable)
        self.menuImport.addAction(self.actionImportScript)
        self.menuExport.addAction(self.actionExportOrso)
        self.menuExport.addAction(self.actionExportData)
        self.menuExport.addAction(self.actionExportTable)
        self.menuExport.addAction(self.actionExportScript)
        self.menuPrint.addAction(self.actionPublishPlot)
        self.menuPrint.addAction(self.actionPrintPlot)
        self.menuPrint.addAction(self.actionPrintGrid)
        self.menuPrint.addAction(self.actionPrintScript)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionHistory)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopyGraph)
        self.menuEdit.addAction(self.actionCopySimulation)
        self.menuEdit.addAction(self.actionCopyTable)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFindReplace)
        self.menuEdit.addAction(self.actionOpenInEditor)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuData.menuAction())
        self.menuData.addAction(self.actionNewDataSet)
        self.menuData.addAction(self.actionDeleteDataSet)
        self.menuData.addAction(self.actionLowerData)
        self.menuData.addAction(self.actionRaiseData)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionToggleShow)
        self.menuData.addAction(self.actionToggleUse)
        self.menuData.addAction(self.actionToggleError)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionCalculations)
        self.menuView.addAction(self.actionValueAsSlider)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionPlotMarkers)
        self.menuView.addAction(self.menuAutoColor.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionUseToggleShow)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuYScale.menuAction())
        self.menuView.addAction(self.menuXScale.menuAction())
        self.menuAutoColor.addAction(self.actionColorNone)
        self.menuAutoColor.addAction(self.actionColorCycle1)
        self.menuAutoColor.addAction(self.actionColorCycle2)
        self.menuYScale.addAction(self.actionYScaleLog)
        self.menuYScale.addAction(self.actionYScaleLin)
        self.menuXScale.addAction(self.actionXScaleLog)
        self.menuXScale.addAction(self.actionXScaleLin)
        self.menuModel.addAction(self.actionSimulateAutomatically)
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionSimulate)
        self.menuModel.addAction(self.actionEvaluate)
        self.menuModel.addAction(self.actionUseCuda)
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionStartFit)
        self.menuModel.addAction(self.actionStopFit)
        self.menuModel.addAction(self.actionResumeFit)
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionAnalyzeFit)
        self.menuSettings.addAction(self.menuPlugins.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionOptimizer)
        self.menuSettings.addAction(self.actionDataLoader)
        self.menuSettings.addAction(self.actionImportSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionStartupProfile)
        self.menuSettings.addAction(self.actionSelectExternalEditor)
        self.menuHelp.addAction(self.actionModelsHelp)
        self.menuHelp.addAction(self.actionFomHelp)
        self.menuHelp.addAction(self.actionPluginsHelp)
        self.menuHelp.addAction(self.actionDataLoadersHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionOpenExamples)
        self.menuHelp.addAction(self.actionOpenManual)
        self.menuHelp.addAction(self.actionOpenHomepage)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCollectDebugInfo)
        self.toolbarMain.addAction(self.actionNewModel)
        self.toolbarMain.addAction(self.actionNewFromFile)
        self.toolbarMain.addAction(self.actionOpenModel)
        self.toolbarMain.addAction(self.actionSaveModel)
        self.toolbarMain.addSeparator()
        self.toolbarMain.addAction(self.actionSimulate)
        self.toolbarMain.addSeparator()
        self.toolbarMain.addAction(self.actionStartFit)
        self.toolbarMain.addAction(self.actionStopFit)
        self.toolbarMain.addAction(self.actionResumeFit)
        self.toolbarMain.addAction(self.actionCalcErrorBars)
        self.toolbarMain.addAction(self.actionErrorStatistics)

        self.retranslateUi(GenxMainWindowUI)

        QMetaObject.connectSlotsByName(GenxMainWindowUI)
    # setupUi

    def retranslateUi(self, GenxMainWindowUI):
        GenxMainWindowUI.setWindowTitle(QCoreApplication.translate("GenxMainWindowUI", u"GenX", None))
        self.actionNewModel.setText(QCoreApplication.translate("GenxMainWindowUI", u"New...", None))
#if QT_CONFIG(shortcut)
        self.actionNewModel.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionNewFromFile.setText(QCoreApplication.translate("GenxMainWindowUI", u"New from file...", None))
#if QT_CONFIG(shortcut)
        self.actionNewFromFile.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenModel.setText(QCoreApplication.translate("GenxMainWindowUI", u"Open...", None))
#if QT_CONFIG(shortcut)
        self.actionOpenModel.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveModel.setText(QCoreApplication.translate("GenxMainWindowUI", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSaveModel.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveModelAs.setText(QCoreApplication.translate("GenxMainWindowUI", u"Save As...", None))
        self.actionQuit.setText(QCoreApplication.translate("GenxMainWindowUI", u"&Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionBatchDialog.setText(QCoreApplication.translate("GenxMainWindowUI", u"Batch dialog...", None))
        self.actionImportData.setText(QCoreApplication.translate("GenxMainWindowUI", u"Import Data...", None))
#if QT_CONFIG(shortcut)
        self.actionImportData.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionImportTable.setText(QCoreApplication.translate("GenxMainWindowUI", u"Import Table...", None))
        self.actionImportScript.setText(QCoreApplication.translate("GenxMainWindowUI", u"Import Script...", None))
        self.actionExportOrso.setText(QCoreApplication.translate("GenxMainWindowUI", u"Export ORSO...", None))
        self.actionExportData.setText(QCoreApplication.translate("GenxMainWindowUI", u"Export Data...", None))
        self.actionExportTable.setText(QCoreApplication.translate("GenxMainWindowUI", u"Export Table...", None))
        self.actionExportScript.setText(QCoreApplication.translate("GenxMainWindowUI", u"Export Script...", None))
        self.actionPublishPlot.setText(QCoreApplication.translate("GenxMainWindowUI", u"Publish Plot...", None))
#if QT_CONFIG(shortcut)
        self.actionPublishPlot.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrintPlot.setText(QCoreApplication.translate("GenxMainWindowUI", u"Print Plot...", None))
#if QT_CONFIG(shortcut)
        self.actionPrintPlot.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrintGrid.setText(QCoreApplication.translate("GenxMainWindowUI", u"Print Grid...", None))
        self.actionPrintScript.setText(QCoreApplication.translate("GenxMainWindowUI", u"Print Script...", None))
        self.actionUndo.setText(QCoreApplication.translate("GenxMainWindowUI", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("GenxMainWindowUI", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionHistory.setText(QCoreApplication.translate("GenxMainWindowUI", u"History...", None))
        self.actionCopyGraph.setText(QCoreApplication.translate("GenxMainWindowUI", u"Copy Graph", None))
        self.actionCopySimulation.setText(QCoreApplication.translate("GenxMainWindowUI", u"Copy Simulation", None))
        self.actionCopyTable.setText(QCoreApplication.translate("GenxMainWindowUI", u"Copy Table", None))
        self.actionFindReplace.setText(QCoreApplication.translate("GenxMainWindowUI", u"Find/Replace...", None))
#if QT_CONFIG(shortcut)
        self.actionFindReplace.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenInEditor.setText(QCoreApplication.translate("GenxMainWindowUI", u"Open in Editor", None))
#if QT_CONFIG(shortcut)
        self.actionOpenInEditor.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionNewDataSet.setText(QCoreApplication.translate("GenxMainWindowUI", u"New data set", None))
#if QT_CONFIG(shortcut)
        self.actionNewDataSet.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeleteDataSet.setText(QCoreApplication.translate("GenxMainWindowUI", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.actionDeleteDataSet.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionLowerData.setText(QCoreApplication.translate("GenxMainWindowUI", u"Lower item", None))
#if QT_CONFIG(shortcut)
        self.actionLowerData.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionRaiseData.setText(QCoreApplication.translate("GenxMainWindowUI", u"Raise item", None))
#if QT_CONFIG(shortcut)
        self.actionRaiseData.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionToggleShow.setText(QCoreApplication.translate("GenxMainWindowUI", u"Toggle Show", None))
#if QT_CONFIG(shortcut)
        self.actionToggleShow.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionToggleUse.setText(QCoreApplication.translate("GenxMainWindowUI", u"Toggle Use", None))
#if QT_CONFIG(shortcut)
        self.actionToggleUse.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+U", None))
#endif // QT_CONFIG(shortcut)
        self.actionToggleError.setText(QCoreApplication.translate("GenxMainWindowUI", u"Toggle Error", None))
#if QT_CONFIG(shortcut)
        self.actionToggleError.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionCalculations.setText(QCoreApplication.translate("GenxMainWindowUI", u"Calculations...", None))
#if QT_CONFIG(shortcut)
        self.actionCalculations.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionValueAsSlider.setText(QCoreApplication.translate("GenxMainWindowUI", u"Value as slider", None))
        self.actionPlotMarkers.setText(QCoreApplication.translate("GenxMainWindowUI", u"Plot Markers", None))
#if QT_CONFIG(shortcut)
        self.actionPlotMarkers.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionUseToggleShow.setText(QCoreApplication.translate("GenxMainWindowUI", u"Use Toggle Show", None))
        self.actionColorNone.setText(QCoreApplication.translate("GenxMainWindowUI", u"none", None))
        self.actionColorCycle1.setText(QCoreApplication.translate("GenxMainWindowUI", u"cycle1", None))
        self.actionColorCycle2.setText(QCoreApplication.translate("GenxMainWindowUI", u"cycle2", None))
        self.actionYScaleLog.setText(QCoreApplication.translate("GenxMainWindowUI", u"log", None))
        self.actionYScaleLin.setText(QCoreApplication.translate("GenxMainWindowUI", u"lin", None))
        self.actionXScaleLog.setText(QCoreApplication.translate("GenxMainWindowUI", u"log", None))
        self.actionXScaleLin.setText(QCoreApplication.translate("GenxMainWindowUI", u"lin", None))
        self.actionSimulateAutomatically.setText(QCoreApplication.translate("GenxMainWindowUI", u"Simulate Automatically", None))
        self.actionSimulate.setText(QCoreApplication.translate("GenxMainWindowUI", u"Simulate", None))
#if QT_CONFIG(shortcut)
        self.actionSimulate.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"F9", None))
#endif // QT_CONFIG(shortcut)
        self.actionEvaluate.setText(QCoreApplication.translate("GenxMainWindowUI", u"Evaluate", None))
#if QT_CONFIG(shortcut)
        self.actionEvaluate.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionUseCuda.setText(QCoreApplication.translate("GenxMainWindowUI", u"Use CUDA", None))
        self.actionStartFit.setText(QCoreApplication.translate("GenxMainWindowUI", u"Start Fit", None))
#if QT_CONFIG(shortcut)
        self.actionStartFit.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionStopFit.setText(QCoreApplication.translate("GenxMainWindowUI", u"Halt Fit", None))
#if QT_CONFIG(shortcut)
        self.actionStopFit.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionResumeFit.setText(QCoreApplication.translate("GenxMainWindowUI", u"Resume Fit", None))
#if QT_CONFIG(shortcut)
        self.actionResumeFit.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnalyzeFit.setText(QCoreApplication.translate("GenxMainWindowUI", u"Analyze fit", None))
        self.actionCalcErrorBars.setText(QCoreApplication.translate("GenxMainWindowUI", u"Calculate errorbars", None))
        self.actionErrorStatistics.setText(QCoreApplication.translate("GenxMainWindowUI", u"Error Statistics", None))
        self.actionOptimizer.setText(QCoreApplication.translate("GenxMainWindowUI", u"Optimizer...", None))
#if QT_CONFIG(shortcut)
        self.actionOptimizer.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionDataLoader.setText(QCoreApplication.translate("GenxMainWindowUI", u"Data Loader...", None))
#if QT_CONFIG(shortcut)
        self.actionDataLoader.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionImportSettings.setText(QCoreApplication.translate("GenxMainWindowUI", u"Import settings...", None))
#if QT_CONFIG(shortcut)
        self.actionImportSettings.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionStartupProfile.setText(QCoreApplication.translate("GenxMainWindowUI", u"Startup Profile...", None))
        self.actionSelectExternalEditor.setText(QCoreApplication.translate("GenxMainWindowUI", u"Select External Editor...", None))
        self.actionModelsHelp.setText(QCoreApplication.translate("GenxMainWindowUI", u"Models Help...", None))
        self.actionFomHelp.setText(QCoreApplication.translate("GenxMainWindowUI", u"FOM Help", None))
        self.actionPluginsHelp.setText(QCoreApplication.translate("GenxMainWindowUI", u"Plugins Help...", None))
        self.actionDataLoadersHelp.setText(QCoreApplication.translate("GenxMainWindowUI", u"Data loaders Help...", None))
        self.actionOpenExamples.setText(QCoreApplication.translate("GenxMainWindowUI", u"Open Examples...", None))
        self.actionOpenManual.setText(QCoreApplication.translate("GenxMainWindowUI", u"Open Manual...", None))
        self.actionOpenHomepage.setText(QCoreApplication.translate("GenxMainWindowUI", u"Open Homepage...", None))
        self.actionAbout.setText(QCoreApplication.translate("GenxMainWindowUI", u"About...", None))
        self.actionCollectDebugInfo.setText(QCoreApplication.translate("GenxMainWindowUI", u"Collect Debug Info...", None))
#if QT_CONFIG(shortcut)
        self.actionCollectDebugInfo.setShortcut(QCoreApplication.translate("GenxMainWindowUI", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.tabData), QCoreApplication.translate("GenxMainWindowUI", u"Data", None))
        self.leftTabWidget.setTabText(self.leftTabWidget.indexOf(self.tabView), QCoreApplication.translate("GenxMainWindowUI", u"View", None))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.plotTabData), QCoreApplication.translate("GenxMainWindowUI", u"Data", None))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.plotTabFom), QCoreApplication.translate("GenxMainWindowUI", u"FOM", None))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.plotTabPars), QCoreApplication.translate("GenxMainWindowUI", u"Pars", None))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.plotTabFomScans), QCoreApplication.translate("GenxMainWindowUI", u"FOM scans", None))
        self.pluginTabWidget.setTabText(self.pluginTabWidget.indexOf(self.pluginTabEmpty), QCoreApplication.translate("GenxMainWindowUI", u"Empty Tab", None))
        self.inputTabWidget.setTabText(self.inputTabWidget.indexOf(self.inputTabGrid), QCoreApplication.translate("GenxMainWindowUI", u"Grid", None))
        self.inputTabWidget.setTabText(self.inputTabWidget.indexOf(self.inputTabScript), QCoreApplication.translate("GenxMainWindowUI", u"Script", None))
        self.menuFile.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&File", None))
        self.menuImport.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Import", None))
        self.menuExport.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Export", None))
        self.menuPrint.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Print", None))
        self.menuEdit.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&Edit", None))
        self.menuData.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Data", None))
        self.menuView.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&View", None))
        self.menuAutoColor.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Auto Color", None))
        self.menuYScale.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"y scale", None))
        self.menuXScale.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"x scale", None))
        self.menuModel.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&Model", None))
        self.menuSettings.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&Settings", None))
        self.menuPlugins.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"Plugins", None))
        self.menuHelp.setTitle(QCoreApplication.translate("GenxMainWindowUI", u"&Help", None))
        self.toolbarMain.setWindowTitle(QCoreApplication.translate("GenxMainWindowUI", u"Main", None))
    # retranslateUi

