#----------------------------------------------------------------------
# This file was generated by exportimages.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAJOSURBVDiNrZTPaxNBFMe/M5udWdJsAkWSVgr2IIoglh5EqhYKBQn231Dv9ageVGhRwUP/"
    "CQXxIrQXgySo6EUPetCLP0BqD9XUsGnYmdnNPA/5ta3ZoMUH7zLL++x77zvfYUSE/xmZtA+M"
    "MTYxnb9ZOJRb5BnOHMYRW6Kg3qpsfdq5TSmdpAKzeVm+cOnk8tLlWV8KD718dP/lzIO7L94A"
    "2BhWx9OAhaKYP3p63Fc6RDLPLB3PjU/65/55ZGstVKSgdAgi6qcxChY2rWwUEDBaI9QhbAKo"
    "jcIIXgfIGGMy75SzBWeeMwDgiJRdiNoaSg06tESIrEGrqRaOnCiu9hZW/x5UdxuqAgCMiOCX"
    "nFvHymJ5ambMF66AcCU8z0NpOt8RQ/ZEkZDCQ2PLwGEupCshhMC72rfg8dqre1tfdlYyAODm"
    "aHHqvPWlMJCCQ4oMpGjv25/tJqEwOVDdEx6Wrszmnz18Xwaw0h0ZDAC00bDd0Wh/wv55llgF"
    "ceJDRYkiM6Ro0F1qtu1AFLLYc+vjOEr8PQFDGtAiimLqA3WLVT4/bc+UTvFcD8p4BH9iAEuu"
    "YmczRIZ3xHNdgY/PfzSDerjeV5kxxpwsLmYLvO+AWNPC2auZuVyJI2k9Ved4cmPztZd1awAD"
    "B9D4pauqEVUGI3eMvoGEP/OHnVWymCOiPWqHoQPhsdr219a11Iv9N6GN6lrPRUwHsN6wMJGG"
    "NvFI66W+NmFgq9sfbLD/fPOtabYacTWtjo16sceKznXpU5l1dg+yIBOw9d2f7TsHAh4kfgM8"
    "Aqsf855uFAAAAABJRU5ErkJggg==")
getaddData = add.GetData
getaddImage = add.GetImage
getaddBitmap = add.GetBitmap

#----------------------------------------------------------------------
add_simulation = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAOCSURBVDiNrZRbTFxVFIa/s8/MPoczEy4dLgIKIUrBkkKlhCaaSokxfdGE9EW0PCgvjS9G"
    "Eu+JjYkxpk2MttRb1cZgaprwoCb6UJTSGlBp04iAkNSWQUIzhQ5kuMycc+Zytg84pNZC1biS"
    "/2nn//Zae6214X8ObZMzUb411J23xWzUhBC60PGU8pYXE8Mzk9e7AHUrk28jWn6xub+tq77z"
    "wX3bTEOaZNV/arThwxdOX4hGlk/+K6AR9NeVVgdNx7VRSq2rZmdZjpVrbCdya9+GQPBwkg43"
    "AxOJBHY8WQS0AFFgFli6LdBLe7iui+3aeEqxsujQf+wXnGsrdDxa1F5VWfnY7FU7MTWTcMPT"
    "q6tLK+mLl6fiz2SBIhDSO4Su1SEEAnDi6ZZkai3D2JzNwKEx3j14L7XV1QDWn75ANoF3jl+5"
    "67lXxz/wAeSWie66Ntl5R41lSr+B9BtIaWAVguPYDB2fpufwdspLTS6MxDh45AoZBELT2BIU"
    "HGgvx5C6XC/ZZ6kdRTsypk8m8UuBlDqG9OEkbRQKM52hvNQE4M2Pw+x7azeBYABDmqRtjc8/"
    "GaHvxG8a4AkAtLV5dJNrb+bcpBtHbndjPr0vDTLw2RjhiQi66fFIVzNWad7PwPDfmpJKJVFK"
    "4d3Q2SU3RcLOYOXodHVW8fT+Ss79EOW7L8fpOzRMRVM5mtA8ILMGVH+d+nQ6tQ7zlEdJq6Tj"
    "2YucOHwf+Xl+TEOwt7WYva3FAJwZjPJjb7wOMHUA3RD1MkCDT+JPJSCVgGTcQxgZAMwCHS+k"
    "8/6R3/l+aAEyECqQBKy1fKoqLGrutnxD5xfd7C5rZi5PaFLUZ7NUKdXywPO+XcESQSomCd1p"
    "YUiTWFjx7RuRqVCBkSktMoo+PdaYX1Vh4XmKnQ+d7RdZv7PMSTvqvZiVP0c7C5ByFCNHk0z0"
    "xFmMxNGMNCKg9U5NrW4dGl7Y9VFPeA5AKcBT2iarl70K9uwp5JUDtbzWPcHU1Tj50t9WfI+s"
    "Mvyi4cn2ykKAb/quuUur6a9uDwS8jKK2Osipo80AzF13a4CakiIDgNHxZe/l138dm5m139sQ"
    "mE54o7FpYZc1aTmXlmK0PH6Oh+8voWlbAYUhA9fNcHpg3v3i68j85KWV85fD8aeA9KYfbLBU"
    "vC0DqhkNAWipBDm6o0cKLPlTKqMS89HkZDKZGQQW/kml/yn+AHcRls69ooN1AAAAAElFTkSu"
    "QmCC")
getadd_simulationData = add_simulation.GetData
getadd_simulationImage = add_simulation.GetImage
getadd_simulationBitmap = add_simulation.GetBitmap

#----------------------------------------------------------------------
calc = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKtSURBVDiNrZTfS5NRGMe/7zanJeY29wNqi3K7UGFqqFCRlRhImf24GSEWQb/+gy7CfhjR"
    "hfQDkW66lSDKFK2VF5Usl1ZCznemS8ic23Az216XrW1n8+lCMt07hhd+4Vyc5z3nc77P857z"
    "cESEjZRs9YTjuNrs7OzLUqlUuZ7NyWQyFIvFWonozQpjtUO5XB6oPrBPPT7xTSIEgxlhCpUK"
    "JcXGpQGbfT4ej+vSOmSMaVkSiOeboTPvzgj8NfMBLBmRMMa0q+Oy1IWCEIY8zwROIvq0RvK8"
    "rRCEz6K4JDWgUuQjHvaBlhIZRzzsg0qRLwKKbFgsJ+Bvfwjf4GBGh9v0elgsF2Hrf5sZaNhu"
    "QOezjoywf/o+NS2KiVKeC8yhrrYedYfqEfAH8M5mR/XeGpw9cx6MMdy724Y9VdVob3uQ9hAR"
    "cHbWD5ZIgLEEvF4fnLwTOTmb4J/1IxgMgXc4kZe/BQ4Hj3SPYs095DiOeq3dyMparoTeoAcA"
    "uFxfodPpoFQqwBjDxLgLxSVF8Hp8OFZ/EkTErUCIaGUAoEePO6iopIiMJiO97u+jrp4npDfo"
    "qaKygoZHhujW7RZSazTUdLqReq3dtIz4zxCl7J5248fcPBYWwuD5Mby3DyEWi8PtdmPG7YHV"
    "2gepTAabbQDRP9H1pRyNRcEYQ2mpGQDw6eMwNBoNdhbuAGMM9oFBlO8qgxASRCmLHALApGsS"
    "X8bGAQCMMThGeHg8XgBA8GcQ/CgPISSk2yquYfO1K6RQKkmpKqDrLc3U2HSKCjQa2pybS93P"
    "O6nQWEgFWi2p1Wrq6nkqqqHoYldWVeBgzX5EIhE0HG/A78VFTE1No7y8FCaTETduXsWd1vu4"
    "cOkcZDLxexe1ryNHD6vLysxpS5Gq0VHn0ssXr9a0r9SfsrENdiP0Fw+QfVq+yoJ+AAAAAElF"
    "TkSuQmCC")
getcalcData = calc.GetData
getcalcImage = calc.GetImage
getcalcBitmap = calc.GetBitmap

#----------------------------------------------------------------------
calc_error_bar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAZOSURBVFiFtZdtcFRXGcd/5+7dN9jsJgQcKIQgCS+1HYMEWqBEW/qmtB2HQMqLLUWpUxRq"
    "EbR+qDp+029FoaWIttWBYdAhzqDN4LS0zgCSUAINb4PQoQtNTDBLstnXu3f3nscPSSOb3bRJ"
    "M/5nzpy9z+z/nP/5P88591wlIowFSikXMOlzUHtFJGN+8lRfX3+nbdtPOY7jG80oUwKBlb50"
    "+gsuEADR2hKR3GfxItCrlKo1AdatW7e4rKzsHwsW1hp+v8/8LPLtSEW6uX75MoYyEBFyudy4"
    "rG3H0Np+ECa+B1EHignKANoEcBznuaV1S8yHH3nISCZTnD59hls9vSMSsHLDBsb5fdTOn0cw"
    "FKSl5X05eOBPzUcOH36vG36ZhuYeWFGEaotIvwARHSwJBg0twq937EJ8kxF3YOQ25KK0NO/l"
    "pZ++SHn5BGWaZoCBVSvQImINR82zu729HQc346bMG/nkA7CyCa5e+XDUPOP2h1w2h8scVQ0O"
    "Qple7Kw9NgFKKUSczyUA0SjUqGl5KZg69Q7sVBTV14HLWzLiQbSdxIp1UVVdRTgcJpfLGRpm"
    "tAMZmKiUKhORolWdJ8Dj8fD0+rUcffcY0ciVEQsIBcbzzTWrCIfDbN+ylavXrt1bWV4+b9bU"
    "qbh6e+dfuXmzs8Tv705Y1iYReWtYAQDV1VVUV1eNeHIArTU7d+zk9T172X7XXdSvX6/Gl5X5"
    "fMEgvlDI9JaUmMeuXZv2rV27DgZ8vr8kM5nviUiiqABHa8IfhTFNk+mVFYN57ej4N+l0msrK"
    "StzuflpPTy/d3RGONDXR9Mab7J01i4pQiGwshqUUaI2IIFpTN3MmV19+efwzu3evfPv8eT+w"
    "qqiAvXt+TyKZQjsOVVVfZOWqFbzz9ru0tp7F5TJxuQx+uO15rl//mP37DpBIJGg8cIAdZWUE"
    "UinS0Wj/pLc1BpovFGLf5s3+Odu2PaqUqheRRmOogHQqDcpAGQbxeBygv1cKDAPbzqBFSCWT"
    "KENx4uhRnszlCMbjWH19WNEo6U9pLtvm4AsvBPwez++KOvDtjc/wwdk23G6Tr9T2H0jLH/8G"
    "U858QDKZoqbmbgylmHPnHB53HN7Y81uWiJBNpwftFhHQun/lA73clo75kycT8PncSqnqAgGl"
    "pSHuf+CreTGvx8OiRffkxQyl8Pt9TPB68WezAOQsi/QQ+4ulQkSomTZNv3Pp0oICAceP/ZPj"
    "x04AsLTuPpbWLeHmzf/wxz/sJ5fLMmnSRJ797nfIOQ47f/MKE+z808/JZLCi0YJVD+3nlJeP"
    "P6rU3AIBLc2nGB8qHfy9tG4JFy9cQqMIlpXTHekh2tdHPBbH7x9Hlyo8/Zxstr8Yb0vDUAEX"
    "2tuTInK5oAgfe2I5krWRrM1jTywHYMHCWiaWl2Il4tR8+W5KQyGmVUxlwcJa4o5DukAC6Fwu"
    "r/isaHSwSK2+Ps53dRnA6QIH5s6dzdy5s/NiwWAJGzduyIspFKtWreDQvv2cbD3DMq0LRIjW"
    "hdtSa9p6ekjZdlZEPixwACASuUUkcisvFovH6erqQuv/3SEzmQxbfryNRq+X7mIDAYj0r3qg"
    "RXt6+Elra8JynGehyDb888FDfBS+DkBlZQWr1zTQ1naOpr8dwfR4cBmKrdt+QDwW45Wdr+Hx"
    "+vhSTQ27z53j+VSKsmF0WLEYaa15NRJJJ3K5v4tIIwx5HQN0dnbicrtxud10dnUB0NHRiXKZ"
    "mG43lmWRtW16e6Mow8DldlNTW8vS1Q383O/nuFIUJgMuAVsSieRZyzqU1nrDJ/ECB9Y9vZaT"
    "J04iAkvuWwTAsmVfw+M26evro2ZeDV6vlxkzKnnwofsJh29QOb2CexYt5Mm1q9n63Pd5/foN"
    "maS1NQP8nZBtB8eAiAWbROu8t6ESERoaGhpXr2lYsWjxvcMYOHJcvHiJV3e91tx0+HDrbNh8"
    "A04l4OvD3QcMAMMw3r9w/qJtWcPeHUeEbDbLubbzWaDFgHAF4IXIcJPDQAoCgcCuy5f/9fDP"
    "XvpFnVKq6M4YCaQfZ2Kx2K+Ap0ZK+r80D/zoUZByeOvT/jeqr6BiUEpNB5YPjbtgMUAapiul"
    "NhWhnhKRM2qsH6fjlOp4AO4odpmvAD4ehtcECQtmjt0B2N4ML46W54W/pkW6x+zAWPFfj86r"
    "+30F//gAAAAASUVORK5CYII=")
getcalc_error_barData = calc_error_bar.GetData
getcalc_error_barImage = calc_error_bar.GetImage
getcalc_error_barBitmap = calc_error_bar.GetBitmap

#----------------------------------------------------------------------
delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMHSURBVDiNrZRPaBxVHMc/b3ZmZzdrt91JM93dBJOm1ISOBOrFXgqGFhTJpdgchaJU6dlo"
    "FEVUelBUCDaEnotHKVgbemgLSfXQg/QicZcYbXvQrLtp2i67JM6+nZ+H7o6zf/CiD74MzPfx"
    "fe/7fd/3lIjwfw6j+4etlDeeyVx5OpNZVErt7+aVUplDrrswkcstp+Lxoz2KIhJiMJE48bzr"
    "bn4/Oyvfnjolhx3nZyDb5gH38IEDaz/Mzwe/LyzIi1NTpWw6/XJUQ7Ut77Osk8+k05e+OnYs"
    "N5BMYto2Fa157fr14m8PH04DMj44uPLNmTOTh3I5YraNmCazS0ulH+/dO1upVq8CTwSVUlPP"
    "7dlz7QvPyycTCUzbfoJEgorWvH7zZkHA+Pr06Ylx1/2Ht22wLF65eHFzZX19xvf9O0pEGLas"
    "7z4fHZ3JplIdk9vYDgJUPM6I4/TlK7u7vHThwvJGuTxjAjSC4G6pWhVHRAWNBoHWBFrTbGGv"
    "bWOK4NdqBI1GiGajQVNr7lcqaK3vRy07I4Zx60PH8fIDA727iMbQQqz1Lfs+r16+XFzf2jou"
    "IlvhoSilBkcMY/X9dNob7icaEWkvUtaaN27cKPyyvT0tIn+GO4x0zBlRavWDVOrZbDKJmUh0"
    "ikTwSIRzt28XNqrVF0Sk3NYw+/WysbODHwQ0tcaMZBbN12/N7Sl+1HIeVufAc1tkLB7/V+sP"
    "gLm1tcKvtVqnZaWUk4dbb4M31HvVwsz62d8G3ioWi3fr9eMismUADMFHb8KRbrEwgt1d/qrV"
    "8KOo1/HrdfZpzXtjY5NZ2/44zNCAgw6oPnoAPAICrXFa+YU9bXUxHYsRg9GOq3cErr0D+e5T"
    "egB8CoUmGO/ChAuoWCy0rGyb848fb/60szPji9wJD+UppU6OwaU5yFkRsc+g+AdMA5KFlXmY"
    "DKOxLL4MgtIGnK1qfTXMqI29cMKDzUWQ8yDD0PN85WDtEwiWQKaglIaO56tDUESIg5eFKy4s"
    "Avu7eSAzBAtZWLbgaDev+pXzv4y/AXjkwasgqGbnAAAAAElFTkSuQmCC")
getdeleteData = delete.GetData
getdeleteImage = delete.GetImage
getdeleteBitmap = delete.GetBitmap

#----------------------------------------------------------------------
FOM = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAHTSURBVDiNjZI9aFNRGIaf00QS05YQIqXBDlL8mbQQm0EcAhkcHNJBHF1cXFxEMhSXTh0M"
    "IauSYnLhWnF3MjgkdGwV6lKL6eDUIA0Fe0PzY16Ha8JNvSm+cJaX93vO933nGEn4yRizBMTO"
    "2LuSWsYQljgFCLphbq6u8mJ9nUMgAkwnk8l7zWZzOpFI9KZcBfL5vANcWFkhYAxPJSzcDnRr"
    "fl6/5FEmk1GhUJCfYjE5oBuSmAKQ2G23Od7e9p1mTI0GdDr0JL6NRgDodKjYNrnlZUJDr1wu"
    "U6/XAYhGo1iWRa0G4TC1YcYLsG2bZ8UiIWNcL5VKkc1mAQiFXG61SrvV4sOoJUmjE42qsbV1"
    "/g7m5nQCujqsmfLO5zi8qVTc5/HT3h44Dl2J70NvDNDv83pzk0Gz6Q8olegBltczo49kzBrA"
    "u+Cj+/HbV5KHia+Ba/E4dxYWABgMoPBy0H/QeftqkYMjpLV/OgDI9D/Wv3zW4OH1pVExwP4+"
    "REy7tcjB0ViBd4nDMzOjUi6nU+/y0mmdgB6fzfoCQJcjER1/qv6Wdnb03u5qdlY/QOH/AvyF"
    "pEuBJ32BisHnXVDKNzcJIImfXNoQqEXMmnjReQDBRcFdQWBS5g+Zx7O2hOB01QAAAABJRU5E"
    "rkJggg==")
getFOMData = FOM.GetData
getFOMImage = FOM.GetImage
getFOMBitmap = FOM.GetBitmap

#----------------------------------------------------------------------
genx = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAK+SURBVDiNbZJdSJNRGMf/e88753zfps7P2TRni800FfOrbUZFSiHUhQkRdJOWFRHkTV56"
    "GUUIZRR10W0RCEWWGklJtYz8KDU/sC+zuTZtyuba3nnO24XT1tiBw//hOZzf83+ecxQATuTk"
    "ZBu6eh51AggCCIVVio4LzSUyopYCQKsux9is0lVpeJ5bVvIK1/Zc8Wlba1M3gBUA/rCuAPAX"
    "mktYJIAAsKnjhFpOb0uSE3TJq6p0/S/HrO7rvdupfpn9Nhbk+8KFFADgWnDS9NTMDSccAGSo"
    "sXTyxRW50N7uo775YCgg5+0e+dD0sf16GwARgBBWEYAwNjnC/wfQmU0ucv5M57Frl24lkIAb"
    "WoNynKgAtToQcVmIjMcmR5QbAJ7nlYebG+eKKsqkZEHhIXEiBi37X599+KAjloMICMevAYgy"
    "fKDQaVXLzgWAanI2CaKgBsAiZhC9VzgAIITErVPr6yq/IOCW3H7V1jf2obzoqlFO+DXAPwfi"
    "4I2blUnzw1RWZwh37vcfimU9IsfzYQdKAOLUxJSYah8wHmcgHSnmkDs+29TYcO6C1T3DNAdr"
    "e49cbOmPaoFEtiCY8k2KJZvF4d5mcO0yyBMcR6kzq2bzqKzNdtjfVsRwwhMAtpKS4j22amsA"
    "AIrrDriKjjZ8r64uczLfnGdiej5rMddGvvEaYfD9kDY7U+NKS0sJhh38WAOUFu+z2iyr679t"
    "XYsKjEupojT/eXoq3kcyUxZpWm5P/7i165l9x8uXdr2lPL+bi5hBrLcWa/ZWee9ePd1XX8b1"
    "Jcz0SNwfr8rL55pmPVx5YqKGUwC4vLOstMVqs8iMMYkxFqKUSpTSEKNMopRKq5SGPAsLHO19"
    "blJTxg3r9ItEk7RUYN5yigfwyvHTUTgw8I5AhswYo2xtheP1lMyC2mQvgpLAxZNRye/xP3n8"
    "yfsXsqckpawHuCUAAAAASUVORK5CYII=")
getgenxData = genx.GetData
getgenxImage = genx.GetImage
getgenxBitmap = genx.GetBitmap

#----------------------------------------------------------------------
lines = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAQySURBVFiFvdZ9aNVVHMfx9+d3H13bvE1Xtt1sSzOigqIFRUJOkDDICErQCopKI2gRRERR"
    "28i/7Ansjx4IIkgC6a/+sDBrJhEFiwoTAsWVG6KbDzX3dO/93fPpj9vVrSez7e789zu/wzkv"
    "vt9zvucIUP7mV7NjmdFMCuKR00cK7n+rxDw1Na3tydc70yV0J2ZfOXj70LETu/zDS+PzAYjq"
    "nb1P0iOGZch3JCLeaFuyaFPTmmcWzgsA+zrsOrAMSYtmRzzfkLjw2dbO3sWSVFOAFb4BJqsd"
    "QgIWRvKjyWzm5dZVPa0SNUNExVDaDvpUMHG2WzLUC+5JZrNvtnRuWSGtT9QCIEBtN269ODSV"
    "uyU2GBr+iAJgA0XDdy7xxOCvTd+7f9OcnhDZRpKWrnwmxwW5xxFdQE4QARhbqGx8wIqfHGT4"
    "C+/cVphTQLU1r9zaUNcYNgAvYC0RRObMgCAYstR1ePjQJ3NVK6LpHyNfPn368HDh/RCXHwcG"
    "jMvTxxryMj2L6y5bPBeL/wUA4P7uiaGBYzsd4ocQ+wTxzPFeXrcgeYs6NqdqAgDwgW2FweLu"
    "r0IxPGDTTyX81ZaWyquhpXYAAPf1xUNHSz+B35SYNCCBUYpItzamG7M1BQD4x+5iqRT2AmOV"
    "DgksUEtT/dS1Wj/72vCvAIA4xCds+gUxsiupcDpIqxi5etZpOCdgZOhECflzUMln8qCUIjqb"
    "JknXHMDBRaVy7D1ApfgYGSeAa9L16fxsL6tzAuzuMOHRAewDQEBUC1M2k9Iqru6ZVRrOHQHg"
    "1HixaLtPolQp3QCkbK/L51na3tmb/b+RmFGK/3FQZ2+yPZVYHRLJHYaGM/2oBB4MDh+Ui2E7"
    "o+XBI98yZXeHOQUAtHa+sji9IN4bzIrKUay8HQxBuCBxvGx9aBLvFabGD43s2T9p7yifa97/"
    "DNDtXZk25zcbdxvnqoDq/z9uzQLybzYflVV+tzA6uv94S8eEd9zzj5D/DABYdFNv4wW5zFOR"
    "eBiUM85MR1RnxBQlTtveTdA7pxOF/pMfM/Z3qTkvAEBrR28dF2auTCb1oOS7MIuM0vr7DV0E"
    "xsC7SMQv/nJ08OCfr/HzBgBIvVHLDWRDLt2WTEX3J8R620tAGQnh6W9IG1Q0HHApvDBVLu4e"
    "7usemxVgJuRINl546SULUumNKGw05IGsRFS5OwBh20HmVHB4O1kef33gs/SI3R1mBTgLkdpW"
    "9WRGQ7K5sS59t4kfQGq3VTc9IsbGnpC1Vw7P/Xzyl/1zApgOYe229EUnQy6Tm7wrQl2Iy8Ep"
    "Zjx0VcIeiAmPzSlgBuaKrszSZc3LFaV6MWsqz3ydiYRQ2Q5f1wwAlT2Sv60xl1RxU8BdQLNE"
    "VF1ScLimgGprXfd2XSI+uVLWFvBVgjRQsuibFwCAOjanljS0t2YWRPeCrzcMJQrxa78DB9wM"
    "ej3vMQgAAAAASUVORK5CYII=")
getlinesData = lines.GetData
getlinesImage = lines.GetImage
getlinesBitmap = lines.GetBitmap

#----------------------------------------------------------------------
move_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKaSURBVDiNnZTNTxNRFMXPeW+mnZZ2WvpllKLWgrAgEjWs3NgFunbhhj9C/wOXujEx0YUh"
    "JiZGFya60mDYuJAoAV2IJkqDURDECMEELBb7NddFP6AwBfROZnPz7u+de959jyICtyBJAG0A"
    "dC2lABCAAFgXkZJbneFKAwCEwmbAN6QNTxyKitQmBJYj5aJTyD8iOSUi5f0DzVLaau+95D/U"
    "l1aGVSZYza4v59fmJ1aRxwyAX/sGGoblMfwRn9We0jQ8muJUO3YcrxLDW2t/R6jWLYui1g4A"
    "UKrGAYAQZbBSwmZqfwohokGlAEBQJUrtc0CnVdkuCrUmFXcIEYEGnFYKWwO1aKj6pDQR4ZCV"
    "/1AITahtNAFE6kX/qBCGkBrV+d4MAqKpigBcVTaAJMlIJEQG4yTDUsqFhdyyoUCR8FseilOw"
    "ACRs245Gu7ttkvXbtOWUj8Jr/uRFFQwN0BP3AjiitBmuahIIAMvnRcCKeMoHOoaSyWR/qbiR"
    "+5Nbm4zFYo8B5JqBc3Dgr5g6GB60U2dSZltUlOkjSIg4MLRGNGzjSDKtM5lMvwcb/S9G7i9k"
    "345/WllZafjSaElEiqX82oNSfulafunjDKioTH/dDoTsABKxdnR2JhGPxzDzfuL74pfp4eUf"
    "X++KSOMKNg22iORI3nMKU6tOuXAl3JXpM/wx+CwT8VgYHQcT8KKIV6MPF96MPb317fP0bRFZ"
    "bzo0t+eLpIbhHWyL916N9J47eex4H9KpJKIBjezkk/mpl89uLsxmh7fDdijcorQCYJRk3jR4"
    "3erqHLBUAu/GRuY/vH5+Y3Eue0dEfrvVQkR2/U3TP5DsOTV++uyF2cPdJy4DaNtt/Z7AmiU9"
    "diRxHkBwr7WuHroFSSUiLV+ZevwF90tIOVCvg5gAAAAASUVORK5CYII=")
getmove_downData = move_down.GetData
getmove_downImage = move_down.GetImage
getmove_downBitmap = move_down.GetBitmap

#----------------------------------------------------------------------
move_up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKcSURBVDiNpZS7b1RHGMXPmbmPXd+7a3BishbygwWCQ4IQSJZBUCEqBAUICSV9qpBIkVLR"
    "QP6JFHkoKalSuU6ZVBQIIWgQEZZ4eW3vg13fvY85KWwT5N0lhkz5Sec35zvzfUNJ2M0hSQDQ"
    "fwi83YCCAPPxng9rxqV3Aaz9L2CpVDlbqx+9Nb53cqbbfPkDyV8ktd8LSPL85MHFm0fOfH52"
    "7sBBPLn3x/W03xXJXyW1dg0kaa21F8b2L9woTZ85lZgJFF6MTxYv1MMw+NoaWpI/D4MOAEmG"
    "NoiuRFPHv6vMnj5p4xpWGqsohxZHDtfx2emLdWvtdZGW5I+SmiOBJMf9ykfXon1Hv4lnFz/1"
    "40m4LMVGkuPl6jqisWeY/7iOhXNX58JS6avAL3skf5K0MgAkGfnh+BdhpfZt+EH9sDEWLu2J"
    "xmPhhFa7hxeNdZTDJ5iu7cHsoWMzz5cffdlcfZaQ/E3SGgBwe6zIiXE/8i4bLzhFY8vWH5uL"
    "phdOlPfNV2g8QEIclRGkz9Pm338+YNp5KKf13qvmXz1mS63l5bUdLa93snDid2TtJbQ6eVCd"
    "uqgi+x5yFYIQhI2kj26r/aqx0rjdeXr/drVabQfBVNZuPO4NtCzJAXg9X9HeAx2Q+b8BA0VR"
    "oJ9mcvITACutVqu781HNzsJWnswhIzngzU0jAYmQ8wH4w7RDgZJEKofc4N6ShBGH6UYCN48r"
    "5NwmcVBuhlbfCixYAE7ADpMEJY7Ujd5l0tFR1Pa9W+MlQ0Dv7pDI5ZRTEEBtm4MAA9EbBRzp"
    "MO9n/bzX6Cdrj+GVqn1AgBRm3UbmiiTFQBZbRkZ9wIzjmm/iS9YPZmA8QfQIRnJ5p0iSpWzj"
    "xR1J2e6BpAFQfqMLYjMiB6AnKR2m+wc/3id6aCaPtQAAAABJRU5ErkJggg==")
getmove_upData = move_up.GetData
getmove_upImage = move_up.GetImage
getmove_upBitmap = move_up.GetBitmap

#----------------------------------------------------------------------
new = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABkAAAAcCAYAAACUJBTQAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAVwSURBVEiJjVZNbFRlFD33ez8znZZOacu0hQ4ULTEFoUNBgwYlhMTEmCAoBpHESMLCuGLj"
    "xoSNiSIkxo0bEnShCzUmkBQVCGpAgQihWCig4af1H7VJmb+2w7z37nHx3rRDaYt38833k3vu"
    "Pefe+0aAztiWLet29fSs2NDY2NAKAIAQAElSREiAAijJ6I4UMUpS//jj1vW+voFjR458/Alm"
    "MHvz5nW79u/ftyuby8lINisEIYACAgAKEY27jj60ZMk4IBQRNcaoqjJauy9evNqdyWy42d//"
    "zblpQdasyWxwXcc6cfpMzXenf6iZck8ASM1r8t7a/cafjFIJgsCIiCKMhN3dS3Xt2jVbAEwP"
    "0tBQvwiAeWRlt7+gra0Y+WWFMgg0EY+rqloioiGD4apKMUYUMFi8OJ2akS4RMSStRel2ptsX"
    "BKEDIIo0pCd0alUiB1AFBAFUjIGZEYSEAWhEDC2B+EEgIEhQxISOKCLqeQLAIAQ3QlERqm07"
    "YlmWkCKzZAJRpSVC+n6gP14acIdHRkBlJAEoAkYZRKpAQYFj2/rIqsxoa6rlTpTl9CDhpVqq"
    "wnLZM30/XnKu3Ry0/CCY+pZT9/F4jPNbW/x5Tc2ByCyZADAkjAgYjzvc+vxG3/N8r1KulR4R"
    "qRSCKAiKQI0RTdY3BJZlGUBn1kSEQtJSVQaBaqImQca14lSqVlSfSWSuawtAM6smgAhJKRTH"
    "0D9w2fY8r0KLVlGkAAARSqgLAdB1HV21srs0N5n0RWbXBCQln8/hm5OnTKFYrNxF6U9Kwcom"
    "OppTV6cL0wuC+ro63hfEGIOWVEpe2/kKNfChACPeJ5pSBFr9WwBatqNNc5M0xhjyPiAAYNsW"
    "GhvqhZOBR41HSqU3RCpAkS6QvXv2ztm2ffsYMHt1gSSKxSIu/3QNZa9cBQCJIjSh6GR4RILg"
    "4PVBvLrzMbl89WxiePjf5H1Bsrk8jn17AoXChCZTI6vsJ3K1glEkX0rrU+vbMTT0U1cmk1nW"
    "399/ZVoQYwxSqRRe2b4VGijCSr3boooCoglAgpf7j5pEzBMjZWzdlHabk6v37Htz279lz/JL"
    "ZXqeDz177rdJTVzHxvyWFug9jX1XJqxk1Hf+gln/+DwI8gDLYptRZ+tz6RTESRqJl2Bqi6Wy"
    "M/rsto/PTtA1OjaOazcH4YWazAhUyBfw69DPWNIRSG1tPRgEpCnBtgs2qUmDWAmgAS3/wIfn"
    "x48f/+WDSU2yWfR+dQz5SU3uMq/sQ/wilnc1Yf0TbZKIKwr5YcRdSyyMwTG3XVGrTg0FavmB"
    "b+6c+H7oDDlUmtBkXnMzXn5xC/zAnxbk6pUhlIrX8dzG5bBNAZYZhW0KcEwWwiIck7ehNTUC"
    "t0yj9iefX9ODh/8+MCE8ALiug/b5bVX0320d6YXI5Xpw6PCX2PRMKxJzYjC8AyPhbFS4asQK"
    "xw+FPd2p2OLFXheAixMg46USbgwOwfODe4d6lXV2ZfDRZ2fxaIbIPBxH3I3DkrnwFL5tS5Em"
    "VhJxysu6kndWZ9IbIpCwx0dGbuPg4SMzajLVzpy7hXd2r8CC1joYx4Xnq5eoCQpgvESJjVsm"
    "UVr6UNuDAGBns8XfSbY3NTZi2/Ob4Pv3fKymtZs3huD7I3CcJGA8lMpjYxe+/yfnBUWs7uko"
    "zW2IlXpWdTTX1i6cb/f1DRzdseOFNTU1cXQ+0PG/AADggY40LvX1ypLOeuZyt/W99wcGjn99"
    "4/X+K7f/6eysW93R3riotTXZ1N7e3GV/+mnvu67rWitXdj3d3Ny0EABmG9sVI8HhW3/VC0bz"
    "+w98d+FQ7xebSVaa7HD1W4n+LCD6Rrvhccd9QQCbT65tfRvkyZOnTvXO9vI/srTDZkwtTd4A"
    "AAAASUVORK5CYII=")
getnewData = new.GetData
getnewImage = new.GetImage
getnewBitmap = new.GetBitmap

#----------------------------------------------------------------------
open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAYjSURBVFiFxZddiB5XGcd//+ecmffdLxuTJdCWQIztFpKUBMG2xLS1pcYgiuCNIFIIUir0"
    "zpt64bWCIN4rXtSLgheiKVRooUV6I5omtkmjxjQhbdxus0m36WY/35l5Hi9mdpO3Sclub3Jg"
    "mDkzZ875Pf/nY84oIriTze7o6kDezOBHH/3e1EMP7Xt2584djxVF6nW3AxTRShlm8q4PKCAC"
    "cJBPT8+cOXHi9NGXX37h6OcCePLJR372/PPPPfXuufN5cXkZQiERLQSB8C/etaXe9aWdK5K8"
    "XVxuZt6N2f/qq29Mbd++9++zs+98uCmAycn997744q+/FhHp6F9emTh34ULxqSEBsG/vg0vP"
    "PXNkFlBnvdxdrTqmQ4ceG3v88QNHgF9sCqAodM+uXTu2RkRz+BtPrMzPL64ivDUcb+VWbNu2"
    "tYrwBJIkjwi1MIS7y8y0ffvklrV5N+WCCCzCeeC++zwiHCJaqRWS2muZt+NCEusQa2d3lyRt"
    "GiDnLHdP3WQyMw0GFRIuyd3bByCrJQccwiS5ZIHk/V6vgVabz6WAhEUEklhZWdUrr/21WFxa"
    "EqwHIjdcD93rlYV/51uHr46PjddDhgEc/vL4U3u2L36/TBSRtkipCHICK4KUQAVf39WfbJq6"
    "bOoaF7GyvMzbp0+nuY+vsoFiFiP9fhx45OEYGx272sXFdYBv3l//8ukH2YcAW4DcC5X9UJlD"
    "RQ6VvTg525dBMrWLTYz1+MmPj7T5rnWFurPCpDYJJZCQjKIovlDX1ZLZp1wwmjTJ2jRegwtq"
    "A2uPqA2aBBKBCHfqpibnrPBAUmCd4O3cMoFQSNZ2QCkl6rpZK2DXAaQ1G9p0oa4ERshg7ajb"
    "tK+bhv9Nz3Dy9L/ogrB7L4BuojUlkAJCgvHxMZ44eICyN2q3C8IWohkQkjCBjPACJNydy3Nz"
    "HH/rFEsry7fz/TrO5OTWOPjwVyl76KYYuFWLCNEMIiqTZETdKleWJfv37mb31P0sLC7y2gu/"
    "Yot9hOUe5AIr+kQqsKKHUgGpQLmEVOhvr/9RkYu7dj8w+sNnfvT06G9/9/tnPwugVcG9hahN"
    "NNX6Q7NEUcLxP/+JH0xdJI+OoTKj/ihWjkAxAuUY6o1BbwyVI1h/HBV9KEZsNazf79uemxT4"
    "50zm/flEYQAh1jyqmsrnuPDzb5N6fRoSlSfu3lYQU32a1QQuFF1RdhFhEEJNoNqRQzkqLBXg"
    "6Nq15Q9uAri0aHx3avWzNckXUTlGlKNQ9KEcwSsjlDHLRD0gUgGsAgmUIAyUkWXKkXHwBjnM"
    "fPjxxSGA5UpM9KLzfxv4w0EBNDVRrVz3LSAcdRkrU/teEioS5IT6JSpy228qoh7gGGfPTg8D"
    "/PtKYvdk0xp7q32S1igceQ04NFV31ERdody0FiqwqAmvUXdENNDU0NTMXLqmd8+8f2wIYG7Z"
    "+Mrd9S1WvhFCyGuaeoDqAbIM3uD1AEiYFYCBZeRCZGCJcEgYZS4B17E3z6++dfrNfwwBcL0Y"
    "fXbrar68hmoVJyHLBIZINNUKJiMsgQMY8iDCcIxUjpBSxexHCwsRUQ0BSBvbHUcEeI28af0f"
    "jhlggQQpGyQROWHZUFlAmVCRMGqiqbgytzy/Nl8GaALSBgTovi7QNESqsS4GohqAFZAqmmoV"
    "SyVqKvACmgFRZ8IqqCpkFZevLC0MAVxaoDy4o/P/7TjWIarW96lEaYByiVcDpESoQIhQQmEQ"
    "CZFQ7jH/yQLXlrkyBFB56t0z4RtywTpHXRGWUT1oz7ZKkJAl3FaQpTb/Q4QMk5F9lLf/M8+W"
    "bZMfDAFMlJ42ZP0NKsiE4QgncESDpS6FTVgylAVlxnKGnFHUXF1MTE/PnlybygDGy2iDcVN/"
    "aWr3DtGgaJC3eR5NDd50zxy8aetBtDXizPmZhZdeOv6bIQVGcqTOsA2LAE404NUKwpDa0htt"
    "D/dA3n4Hoh/IHQYDThw7dTTincEQwH/n0uzcit2buL6t2kgLgQYNKmuiWg0VhqoEhRGloYFQ"
    "LyKWGyJV/OGNs5+cm7780yEdu11ub8/kxCGzlACMtAmMtZZQzkFqr6/fTjTkIGJw6r1zr0fE"
    "0NdOd/r3/P9scPiaCWTWOgAAAABJRU5ErkJggg==")
getopenData = open.GetData
getopenImage = open.GetImage
getopenBitmap = open.GetBitmap

#----------------------------------------------------------------------
open_small = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAIpwAACKcBMsYCAwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAOKSURBVDiNrZVNiJZVGIav+7zn/X7VmRodRnRQUzOaWqQRIUR/qxCiFkXLaCWCUGsXboKo"
    "fbTKRRG1c1EgFEWCIG2KJqbMGlMTa2YknJ9vvvfvPE+LmcYgddUNNxw4cMF9n/OcI3fn/1S8"
    "2+aJE2+/cujQw8/leWy74+DujocgW1vLzKyZnr7w/cmTb7zr7nZH4OHDL+84derNt76b+WHs"
    "10vXs/Ug1ut27Ohrr85LMiCFEOzIkWcfu379z8vAp3cE7t+//dHJye2jg2Jo49vGXbihYO08"
    "JnfLQQkkMzNJaWrq/r13jWxmMvN4YN8ek5TWbaBkZlFrCqAkKbgTNoAPjY9PNO4ja6gWAA8e"
    "fmaHpZQj+Zdnz2l6ZiYDHNbbk9zdvd/r2evHjs5JCCAeOzTy+PvPr57e1rcJJNTZbKG72X6q"
    "r+GeIu5MHbiPnRNjAC4JECEIx8nz3KuqGJF8Dbh9xA7uu7eZ2MiqgYKy0A+VO2JxcYnllSEh"
    "RAC5m4cQkCAoI48ZVVl0qqqJkvTfDlMtLwe4FQD8PHuJs+e+wctFvBgQQiZCBiGAApu3bOHp"
    "J5/Ii+Ffe44fP751A1gnwXpJSqXcV6mXFzh4YDc7uw3xl08Y71fkm8ZQv4+6I4TeCPRGlHWH"
    "ce+OR1786HT1RQRIwMxCTj/39dpBflWz771ERU7IMqZ29wj1KFblkAlJJAmFQN7uqNPKe+fP"
    "T89Hd/THUsbu0ZqxLqSNSWxwXcQ7I4RN9xAsh6ZGqUapQZaQG5knqnLIhdm55cnJPT+G5Uqt"
    "JoleDt3ckW45pIYslYSmhKaApsDrElKFNyXelChVlINVFm+uzj+wK+vEGDyXHAHma9at641S"
    "hdUlKocQO6gckrIWCjmuSGi1SCGnKKrly78tedzU8qZMIsugSv+GrcnrCuUlwWpkNfIaeSJg"
    "KDjBEnlILCwMVr69cGU5JlTVLjKcxm4zg254U5LKIcrakLVQaINaSJEQckKvzZX5euHMmTMr"
    "0Yyt23qJGOB2vLXzKVFTQCoIqUb84wZ5w+9zKywPqxl3t7gl+q5e7kiiqrlNZkAOZQmhwBkQ"
    "PELKiESGQ5j9s1hh/urHADE4n83M50/1o48asjs94IoGrZLQWnJ1DHWTq11rYDeHF2/wzsKN"
    "5gZAnCsHX20d9l8YuLUt6K7/QWzJ657IhGMiFI1WYyguX6muffj516sfAH8DsTbblud1rvsA"
    "AAAASUVORK5CYII=")
getopen_smallData = open_small.GetData
getopen_smallImage = open_small.GetImage
getopen_smallBitmap = open_small.GetBitmap

#----------------------------------------------------------------------
par_proj = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAO7SURBVDiNrZRdaBxVFMf/dz52NzuZ7G6axOx2k41L2hKb1JZoG0vTShUJCoW+FBJEiqCg"
    "D74oKPom+mYfFHzJQxVBg5KI4Ae1bRAqFUuhSbdN4rY1Sdcm3WS/kpndmZ29M3N8SFaSbKMi"
    "Hrgv95zz438+7mVEhP/TJACoC7DnmShENnnI5aaO26IUNNXYY/0ON0v63OWPiMiqhjDGGG1R"
    "xIgIoQ5hqmdQemQTj4DyCvFcEuVCqsmui5yczCfHPygvJ38AgIb2vhflhvAhrt2/oqV+PVvN"
    "EwBAkMFDcYZQnMFTDwgyUBcCIr2C3DMkqE+8lg8Zqc8OQEvfXlcm+hrbD6uxQxHfjo4jjDFh"
    "U8kb7dqnPkP0dC1YhcSi7Lc6Dr8hx2Q/0PmM1TDxufN0MH7sVHDXcVbOzc8Tk7yV/B+TRORu"
    "CxRlwfY0H5kyc/rHRnYmlplyhx/aJwiNnUzwB5RXg10D8wBDPjH2TXZy5AwRmTVD2dQ7W1/O"
    "TI+9yzN3Z5UmvFTfulZOpQg4tjttpqcrTJSYbeWTW2EPBPqbEQBbuii1+uVoH/coLQwAkPoF"
    "RsXwfbU8+904HEciTcsCAFOUMAwjXZ12DfDAaakZcLF2GFwO3LkoVrTFPctqtKm7kLwwVo0N"
    "th98Jbz/9HFjMTHLGHuLiKgGeHPEzmpp2ScIsuxwvmIbfIaEbiPQOeCsJs+1qeGeU8X0za+J"
    "yGZKc6cn2OYj1354NXd9B4BsDXD1HqVJfOqCEuvfZS5NE6fU74xEyt74krfsH9oHUX6BJkhS"
    "WvasCJKcLM6JvFJamqm2YO2lOFCrwJCN6MvzPx0sLl4L84opiWrr4wxwuJ6Be300BHJdr7aw"
    "G2q4DqbmRNLfTzaQG/6CsZ+HiGYlALAEGFWgIaKwk5tvF7jp/TYQGSwFo8+Cl22Z7ASFYp3k"
    "cCba5SlvrC9M3HCjyfPnjll6wgvc+0uhUYAwcdZeAIBCAXyI6JIa2d0lKO1t/sb4XUGQ7xfm"
    "cp8ooqe/XMpZ3Fgd9uVmB5yyntPL2ujGljEiAmNMBSCu3zlEpDfuPfF+fbT3qJ083xbM/GaJ"
    "klfPEKbZ3hMermdMc+7qO6VSavGBe0hE+laHY+bLZBWN7uwtPCn5AhDlwLhVjNzyh254AzuV"
    "4lKiF0ANkG33HzLGvC1e9b03reKj3KvEHanOV7a0leFgdMZQW6/oc5c/JCL+r4Hr0KZB4Mxz"
    "QKMNSD8CyyPA60SU3S6nZg83GhFl44yNzgNHASANXPo72D8q/C/2J1yc2PMtfwF8AAAAAElF"
    "TkSuQmCC")
getpar_projData = par_proj.GetData
getpar_projImage = par_proj.GetImage
getpar_projBitmap = par_proj.GetBitmap

#----------------------------------------------------------------------
par_scan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAOgSURBVDiNrZRbaFxVFIb/tc85c81kMjmdC0k7yaQZ08SWjpZYpIpWiCYt7VtfoiIVaaEY"
    "VAglCForaouKgig+1iJFKSiCmBSqlFSTh9iHJFqtTjE1iWYmaTMzmcnczpy9fMilk2QKeXC9"
    "rc1a3/73v/bexMz4P0NdkzjpkN0lOoi4mcFphpjOz8lB08QIM8c2AyRmhqNuz1aLGh1qeLSw"
    "ZUsrOxw6oVQACguM1BQX/vjWTC7GuYWZU+sB4QPvbjWFPCAs6jc3v+6dFQCg0ej59hP5YOPj"
    "cKhWYO66NOPjsmgsAnUPCqsnRAYAqqTIJG4C41ipKHUAUIlIC0REk0Mn5JOMoQ/M0XxKvmPm"
    "kLDXIqLa6FBxgdvudUTJcAoCFMGLKx4G7DqsAJC9DUC6Z8xc4hIzpwF8D+B9IvIASFcCCsAr"
    "QayVHPHlHP+kJjkPALXNhJ1HMk8FIuJXT4MYr66j85pGDzNzgpnNigoFbyNgLtrfUwAAlZml"
    "y6dciA6YPeFOxe3fTcK/Ww0CQC7BuyaH5WFXQFzLxPkgMxc3TFUiyEJOr+QqAKRnzdfsOv0V"
    "G1NfdTdYGwI7s4q+Qwi7h9ByUKmpbaLHxi/ItwCc3CCREBSShsssWIrcHT6X2PP5DkMeG4n+"
    "sG/gpzPG1Ykr5jwAeFuFpjl433pWaP9pGwFeJkytAonIaqumQdVJXXzxiGlx6F+6Gjt9euub"
    "L0wOyeSqELq7+epala0FAJgxeVcwYKu7n6b9baI6fU3mLTkqaOxwZZQivF1S8e0VajENzLxt"
    "zJyc5+Fy4GyVL5SyuUON8xNXVVl68Wnm6aWnZ6H8tg5FR4eiAXDJUhFCXXJEmsDYOWPukRT3"
    "ALhVDhxo7XodEDPh29E3uoF/V4ZiJKfkdz+eMdqdAfJWeclu85DDyGlqJi5KyZvZP/Np7rtY"
    "4kvlsObOs81SQT2DP+lmHl2d8vL9Or7kE7kA1AMI1Nz3RMRVHzlas8tz+tZA3xoYAJiCnwUo"
    "q3Lxq/L1Nb/N8uu4AeAGEQ26w/u3E3NfcO9Rqhr57CEfEJoFJjLtz/+seMNdAL6I9p9aKGds"
    "mFwZnDXp7GXCmC32+8fH7TXPPaPZHzhhdXXb4tc/AuEXZAufru+7JxAAov09BUPoL3sTf8dY"
    "0Zxpa3W9odlr9XQs61wsvDRx5VR+fQ9t5sduIzrbS/SkEKqFzVLhPfDl35j7KtVuCugn8uvA"
    "Kyse3gE+jDPHK9X+B+XkifTeRn7jAAAAAElFTkSuQmCC")
getpar_scanData = par_scan.GetData
getpar_scanImage = par_scan.GetImage
getpar_scanBitmap = par_scan.GetBitmap

#----------------------------------------------------------------------
plotting = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAJsSURBVDiNrdVdSFNhGAfw/7OdzbO2HTc9zk+YODcDTcUIQqIssI+7opuuvAmhILGiroKu"
    "uu2mu+67jUCjEhSNLiyLwix11pxpSm7uQ9bOdnbO2dONC4lJm/jcvLwvf378n6uXmBkHOSYA"
    "IKLjRDR0EKCwc3YTCQOVracCrOXS+Vw6bmRTM5lEeGq/IMhkdle1XbhRuOvpeM5R3zUo/voc"
    "jAFzzKyUBZqRd9R+HYEqiIhW+1SL7KuoMtPdQSAwAywS0TFmzv0PNP1tZGhB/4/phb7Q5Jq+"
    "8ek1AJitUmMtYG0H/NWAr6yGDGSeAF0ARJuRvWoDn1WcteoY8CoCzG4xL5QFAgAzawA0q8M9"
    "paVjusXtlUcr5Xu5ZPRjKRiwa+Xdo6WTc2pydcVilwXR1XK5VGxPkJkNXYm9AQCLo66PiIrm"
    "SgKJyNJP9Mi/+t6rK/Gso7Gn19nUc2ffYAcwcAUYGlZTZyg4tmESKmBv6L4uSd4THUS3nUQ1"
    "ZYEpYH4J2I4Auntz8amy+SUsyv5ml693/JwoPewHXhIR7QUK/z6sME/XE/VKQHPQUF/YPIHn"
    "zPzY3tB1eESshPR9ogXpRAOA9WIgMTOI6BqAi8x8vlhIrGkKSHLniL3lZBsAZLe+/VQiS6Nq"
    "YvmZur0xwcz5skAAIJfL7XB33LfL/ks2T8ALEPRs0shshRbVeHg8tfbhZtGV9xpOJhMAbpEk"
    "PWgNe97aq5pbY3VHyNl0tJ31zHwhVwCdALxENFwKbkPK2hkLYSE0mZk9JL+DoYOIPMwcKYDL"
    "ABQAp0sBg8D6OiBk8vmo9juS2inmARChg/4C/gBWSPo6odyUjQAAAABJRU5ErkJggg==")
getplottingData = plotting.GetData
getplottingImage = plotting.GetImage
getplottingBitmap = plotting.GetBitmap

#----------------------------------------------------------------------
points = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AANlSURBVFiF7ZbNaxx1GMc/z29mdmeXmt1Jk4BBram02E0lbQ61GKp4qQjb0oOx2Bdfqgge"
    "BNFC8ZK/oDfFkwcRC+KhLXiwFEUU2x62rBUhIq0twdrNS1925tDs7szs4yGxLmut+5JtLj7w"
    "g2HmmXk+8/t9nxdRVVbTzKpGbwQQkWERmUpa1u8J2z4jIvtEJNFzguUjyFoi5aFUavHItm3x"
    "i5s2RY5l1Qx8qqr0comqIiJvpy3r6IXdu+0H1qwR47p8efWqvnnqVFxXfURVZ3u1AQbAgQN7"
    "hobs5O3bREFAFAQ8NzAgCWMAXuhVcAAbIIZC4datsahcdkwqhalWuRiGVOLYAoq9BPhLA08A"
    "8atr18bfjo7WP8vl4vFMJnREfu61Bv6+gLccmFnaECIbvgHGl58NAkcSxlxOGFMEDgGpFQVY"
    "DmSAp4H1DfcSlsg1L5msvDs+Hh/asiVKOU7VFjm9YllwLxOR/bbIJ8V83gxls4jryrnr19lz"
    "4oQCOVX9tRsJtFIJ9z/reWSqVULflygI2N7Xx4PpdMgKZEgrAIULQRBXy2VC3yfyff6Yn9e5"
    "xUUL+KlbgFaO4CGBy5PZrPXG8DCBMfJBqVQ/c/PmfKT6sKrGXRG0pFQ44MBFljIkduAssOO+"
    "iLBpN7YDvqr+0tVfN37z/3mg3RdEZFBE3k9a1pWkbZ8XkddEJNUpQLsacC2Rmb5EIvP65s3O"
    "XBjqF9PT9SiKTkeq+fsB8LJjzMfFfN4azGQQ15XvFxZ08uRJBR5X1UvtArR7BC/t7O+Xvkrl"
    "TlXckc0y4LoRsLfd4J0AnC/6flzzfcIgIPJ9ZkolblQqNvBjJwDttU54VCDa63nx17lc/Pno"
    "aH3C80JHZAYwTV11ly3ylWPMHHAU2Pif7bhFiFccuMRyVbThB2CiyWfKEgmfHxmpTU1MxI95"
    "XsWIVO8G0XEhEpGngBvN7VhEHBuuvZfL9b8zNoZxXbHSaX3y2LHwt3L5Q1U93OjfcSFS1bP/"
    "Mgs8E0H/pOfdEWro+7JvwwbHMeZgs7PdKcA9bFqgXpidNTtFqIchplajUCrFqvrPAXclOlrz"
    "suD4SCJR+2jduvjc1q31wyMjsSUSAru6FmGLQl1vwXGBkCWhLgBTNGRK1yJsxURkGMgB36lq"
    "eFef1W7HfwLrg7K8w73tlwAAAABJRU5ErkJggg==")
getpointsData = points.GetData
getpointsImage = points.GetImage
getpointsBitmap = points.GetBitmap

#----------------------------------------------------------------------
restart_fit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAVxSURBVFiF3ZdrbBRVFMf/5947M4stbgUKyKOVZ3yAUR4CEk0RBYSERKOSCJLoN4ghmkgx"
    "AeMHn2A0GmOiVoKJxoiBD0CisSKgCa8QCaU+QCAU21QkIpS27M7O3Pv3w+72xRbbRb94k8md"
    "mcyc/++ee+acM0ISxQwRWQagleS2ogzkB8miDm30TlESAphVrA2SUMWCC8QopYw2epuIjCzW"
    "Tr8BRESLyBQAwx9+Yr6Mm1h5ved720UkURRBX9wEYCCANcbob5SWNgB28NBkumb7K27P8c/s"
    "wGRpWin1STFbIP8UhCIyy/P158EAf9isByZ7d8y+WabdPQmVY0fBNwl42sfhvb/wyUVrnHPu"
    "eZJv9sujvQGIiAawTkTWTZ0zAStfe0gNHnSDeCYQTwfwTZAFMD48neDmD7/ka9XvO5KLSNZe"
    "E4CIiGh8rZWqWvLcbH3/kimSXW0iNwfwTBai41wHfHHlu27H5l3tzrpJJBv7AtBbEK4QyJxV"
    "H8zTMxaPlTBK544UwugywjiFTJRCGKUQxvl7l3HrlHFCxxIAZX31gCmw+gql5Y05y8erIWMC"
    "CeO0kNlgdXQgHRyZmx0cLZyzPLjrKNdX1ziSq0nWFw+gsfGGkQkz7eEbJYw6xYlOQUsH5yys"
    "sXC0PPVzE9c+9W4M4AOSb/dV/AoAEakCcN/cVaMkYhoSA0R+5Vkxxxg/7j+DE4f+wMLld0GL"
    "z7XLa6I4djudc8/2R7yQB+4qGWIyyQoEmSgt6PheHQDLMJ3B1teP2LrdjSICxnGsfz7QFLW3"
    "pI7Z2C0haa8JQClMGzRWm0ycBojubncxdm9sYP33TW0AFomRTbs2Hx1P8ryzfJBke3/FrwCg"
    "YHqyEiqMUqDrGmgOrRfSOLC1ASSeIblPG6UceZmOC0j+Xox4NwARKQUwunSklUyUEnaNdGdx"
    "9kSEXMbYAgDOcgOAX7tGfK4oDQEgBbQIoJHkX715IPuSEJGNQHQHiGKLHIEAAMmaroZEZAIE"
    "9SC83gA83xwGML0gAMlWZaTxUiMrym8hrIul67deOtrLP7oQwBcFBB4rLUugetNi8XQgnvZh"
    "dABP+/C0z0/fqsXer+rber7ULRMKcfBiA1z+2tEhE6eQidOQASEmzh1ApeU9EZnaY/XzRMkL"
    "9zw23istNygt9zCw3Mf1Q30khwUoGx7gZH1Txsb2u54A3YLQORy6cJqLSeqcYQBAZEM4Okx6"
    "NJCWZps8dyyzX5TUgjgGwZ0Aqm67dyhnPlLRkbxAdmxj64U2NDf86QPYd1UAAIdS5xm0nyNK"
    "hwnJDgZYF4kyDvesTpjmQwme+8kuaD1r5w6uvM6fMGOQTJxZLhmbBnKizKdpxjyy9zdCQBD7"
    "ewJ0q4YioqCxt6xSpsyu1p4SkQ6C/DMQGOPT04lsNTQBfBVIZ3nOV8cEfM9npl24fumO6NKF"
    "1BZaLruqB0g6EXmipYFHT9U6M36+BshuEAQRxaEg72YS0Dl359J2Z9GKsWVDHdtbwvNweLqn"
    "OFCgHJM8SYfVx7c529qcrXuFeobIhrlSnOqcu5yno8v8ofY063Y1wcZuGcmLhQB6bUig8a3x"
    "Mfv2pcobMV1lg4FX7AiU6I6mxNM+PBPQ0z5O7G7jnpqmOM64d0hWFxLvFSAHUQLgdQArRkxT"
    "nPy4Ul6JiHRJMh00FHjahzE+4xbDAx9dipt/TAmJlwG8SjLuN0AXkSql8bEZgOE3VSkvWSGS"
    "rBQkyrIAJJE6D7ScAS41Ck/tjGPneIwxlpOsu6pxoM9teQmAl8SgTgQhAOuVIJ2sRMokstci"
    "CMWgDsAaAOZfa8sLeMQDMBnAVABjAPwK4AiAn0hG/TKGPmzBfz2K/jf83wD8DQrW6m/QehVb"
    "AAAAAElFTkSuQmCC")
getrestart_fitData = restart_fit.GetData
getrestart_fitImage = restart_fit.GetImage
getrestart_fitBitmap = restart_fit.GetBitmap

#----------------------------------------------------------------------
save = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AASqSURBVFiFxZbPa1xVFMc/5973MpNkoE1mJqa11aoUN0pSKxQEG6laXRZcuBBRF6XiSsGF"
    "4ELR/6Ard4ILhSIUDC2KILrQZmOarjQLUaxpbDJGTZrJ/Hj3Hhd33sybmE5mQsULj3ffj3PP"
    "93zP955zRVX5P0eUfRCRPIzuC08j8t+4rCpsrqqq7wIQD9//+Pjhkx/tP3BvzlrBIGKsICIY"
    "EXxtI3eomC/kh/OkyEQ6GDPT9nvJfFyprNeLk4c2RND5ubk1kfJjqqsbbQC5kbHXps+cuyc/"
    "MkJkjUTWEseGyBqiyLDy4/e8++pTcvTofT3juzJ3lQsXvyKOY2rVKu+8fY5icYzX3zofn3n5"
    "7GgUWX3kxJWJ99984xng0zYAxQw5DM55QBDxSNKJyPv+tPLD4i8cefRJnThwkMX5OdbW/pJi"
    "cQyvinMeAbFRbIwZynelAAHnvDQT3/KpgCIoAjjv+wKAKk3npZk4fMZGFZqJE0BdJpYMA14S"
    "5zHeIy4AElp5FEH7ZADAOR+ujI1XJXEhOO8VrJEuAIKQOI8NNCGSOgdx0rXYbiNxnsT5bQy0"
    "U0CSed+1DZ0PKFMAIXhB8HjtLwUK+NY6WdCqSuJCWp1T3E4AVDUYi0Kgq72l+hUhdBjIFjmv"
    "rcgl6MnuBEBE8KqI9zgxCH5gAOXSGF/Pfsny8DB/r60x+uLJDAMhqCwz0fYFVNMt5wEDrZR4"
    "sXxy4XPKE+VMeiAtN229ACdPPNSaP8DlL75FJBCaasDdTgPpotqiLHUuwPDdD7JQ3SL6zRAZ"
    "aRUoizWGOBKsNUTWElsT5pEQGdsuZMefnuow4HowkNIF4BGSFhsihihfwEat6tgCELccRCmA"
    "1jzcbfsbxmZS4ElVuCMAkdADgijDv9KukB26cUImC8HOdebgM/VE2v/5XhrYDkRVcT7Nt+80"
    "ndb27OQ+lO8UT7shSUcl6TyUe98bgLqEzYXPuKtYIKiiE60DnAgNuutFx2FnDsL6epWpZ5+n"
    "fOAg0NJArxQA3Lr5K2dfOM0rLz2HqrLXg4sxhsXFn3jv/EXGJs4AhAppdwHgGluUxvdRqfzB"
    "yspNarXawM7jeIhSqUihMEJ9q7qtDrjeAAAajQbXri1w6dJlbty4gff9MZGKuFgcZ2Zmhqmp"
    "6a5eEOqA3R1AWpqbzSaNRqPvVKQAGo0mziUtO/qrhNmRy+WYnp6iXC5Tq9UGAhDshyiXyxgT"
    "tRsU0NUlewKw1lIulxkfH9+TCEUEYwyVytq2FNymG/ZaKHsAHRQEbGtGrk8GnHNUKhWWl3+n"
    "Vtsa2HkcD1EulwAT2vGgGqjX68zPX2V2dpalpaWBNVAsljh16gmOHTseGGifB5SUg86ZMIx/"
    "LWaMQSRcoITD6q4QEAkdMtjRORWLqFev+NASo212qigoiI2pN5xMT08zOTlJvV4bWIhDQzlK"
    "pSIbGzXEDpF4FKc7a0C9r/pmDWMLABQmj/DBhxf55ruFgR13NR8Rrl9fJn90RpPEI6C16mbD"
    "ueQWgKSLS+7ww6P7D38cDxdGAETC0US9NwN5zwIRMCIYa9UY0ZBKdPPP1aX1ldXTqj/XZK9N"
    "5k6NPUd3p8Y/skaEs17a8qMAAAAASUVORK5CYII=")
getsaveData = save.GetData
getsaveImage = save.GetImage
getsaveBitmap = save.GetBitmap

#----------------------------------------------------------------------
simulate = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AATASURBVFiFxVd/aFZVGH7ec9777YeoY+LUtjAxI9OG1iJdlumyCBHKmuuHlCIWSct/JCGi"
    "UAk1sUASM5SVCxplRamlFGFZ1OiHP+b6oaZkbrLp1DXbt3333vP0x/2Wmpv7vs9JBw73wr3n"
    "eZ73ed/z3nOFJP7PoZkuFJFbRWSxMRIAQmMg3b0XhiGdw1aS1X0mQET6x2Leu2PHjLjqxjEj"
    "DcQAhAAGEAFgQAr+ONqIL7+qJYD6nrAyEmAMXssbmDtkx5ZlJj8/XwCFiI3gREEofJ+YMGm2"
    "r6r1QRAs7zMBIjJLBLM3bahEfp4nYBwCBWkiIcYjYLFk2QbW7T8QhGFYQdLvEwEiUqRq33j6"
    "yTJMm3otLiAXhYhHOh87d9Vzxaq3SLKS5MFLYqa6C0TEqMoXo0YOmfDj14u9WFa2gFYkabmI"
    "AuLxTGucY256xm9qbt3inCvvDTcdBxaJmNKaNytszPNFSJDJvCMip/Mxf8Fad+p0WwvJJ1IB"
    "TUmAiIw3RpatXDLFjr1+AMh4tJQWpEKMks5HVXUtP/z4eyH5CMnTKWH3lgIRyYnFzJ47SotG"
    "bN8800KStlMF0hW98tCRMxxX+krQ0eGvJPlCKuRAag6sysnWa6rW3mbJdjFIkkMBRCnwfYOH"
    "51QHYeD2AViaKnmvAkRkOoCnNq4pwdDBEEEcYETMrtzDYsnyWuyrPx6GIecAUImaQredEQAB"
    "JJi0vscUiEiBp/LzYw8V5a1fPU6IyHpQBcmmQ1GcbAlQOHoTXerfFAJ4h+TsSwrwVD4pKsye"
    "unfnzV5uTnZyu1mRf6s+2n6ExXc/nGLbWYeoFRsANtkZbdItg45OcuGz23issbUdwD0kvwV6"
    "SIGILDAG02rWDTe5WQkREKAFGEWN8+wXUUws6X+uIGHRdS9GCVi0x8EZFe8HTc1tfwMoI7m7"
    "i+siASIy2lqsfnHREFMyPgtkAmAQkSECPCdAo5pIEkbFGT0XUdJZtLY53vvgtmBPXfNpP3BT"
    "SP5yPp/+h9yoosZT8awVvLr+BFQFqoBagaqBWgNrFaoWnqeYNCEfgwflgu6CrkjS4uSpkNPu"
    "/9w/8HvrCd93k0kevijg82tARHKtxQ5rUSAiXhQW1BHKaFqSySssADPv0QK+vuo6Q6iIJMlh"
    "0dgUsOy+b/w/G9qPdSbcnSSPdZfuCxwg2Q7g9u5e7CZV+dZKw+SJOTEjHXRORcSStDhy1GfZ"
    "zN1+04nEwUTClZFs7gkn4xMRgPl5A60pnzEAdL5AAtIJfj3ks+yB3/wzfwV1iQTv7q0lZ3oi"
    "0lgMCyvnDVJVEYIAib3747yr/HAQj7vahM/pJM/2CkYy7QmgXFX843U3hH5DsfMbit2uj0aG"
    "/XJNZ0zxKYDslLEyERDzUPt4RX7gNxS7oLE43F4zIszOMglVvAfASyuYDKIvARD+9Nmo0G8o"
    "dh9UDQ89Fd8aVAGwaeOlu8AYvF16S7/OoLE4rF57dWgNAgOsQXJLX1EBAIYZg8TmjcPDdS8X"
    "hiIIALyUCXGmApYWDtWOFc8PDQUIATx3OeRpCQCQpYqWYQU2BBAAqLxc8nQFzEUUdQBgbl+Q"
    "pytgvwgSAGb1FTnJtDqhJTGT5NY01vQ6Uv4xuVLjH91A1FlWm6+1AAAAAElFTkSuQmCC")
getsimulateData = simulate.GetData
getsimulateImage = simulate.GetImage
getsimulateBitmap = simulate.GetBitmap

#----------------------------------------------------------------------
sort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AANxSURBVDiNrZRbbJRFFMf/57vt9tv7rjQt7fZeutGmpWTBYFKsxpJQrAGVhIYYQSTB+KAi"
    "PkiMURMeFGtiYkJNeENEH7AmBLTw0AcrcmkjkjQtgaV1tfSiXbq38u23u3N8gN3s1jUkhpNM"
    "Mif/mV/Of+bMEDPjYYZUmDxDtHEb0UEikv5rw4NCKUw6gXfqgC1LQAjA4P8BUs5ygKh+L3Bh"
    "HBiuAtKHmV8uuYH8ZVZ3tlzImk4kZxUSseRfvkXm0XRRhV3AbgMYmwU+bwMG/UTeP5gjK4GW"
    "cutq1Vb+isW2aq0giqajc8NwhAcB/A0UnGETsHUCGBpiviSAqU5gT6kKZavTbXFUPKlXtPbo"
    "3qbtstXVjvhta06XAGAzUU8L0NEK9B0hGrEBle3AllJAFSokzc6y7oGsu5k0qwCQbxUFADYA"
    "O4aAM6PA1wBgAvoe4JMNROsvM18pIjITmMGZNETWFMRpUSgrASLHLuDZSeDNi8zf5IRDRDva"
    "gL0AioCsKgSCBBAIAFiiIuB1IPU+sL660rq5pdnenxNEgx5iQGlptvenTWSnwsmPmXlRkpEG"
    "SAAEQIIEMu+Zug9kZhPA9Lo2977jR4PBUuf2xbHQnYET4hQRyfbK9gaLC1YQQBBQFeGpaWys"
    "CQa7zdHR89F82yxF0zP7D17N31YsnnG+d2CNv6e7gi7/uhRVNN0uu6qfV50Vz0kWVy0BcLtd"
    "qtvTugkxZ+LPqclvAfySB976PbktN3c4LI91PeE9u33ratq578rsVDj1UiYpZjWXP6Dqvkfl"
    "Mu8qVdNQV+fXyvXK2vmbKc/k+M8xYMVbBgAi8rU02k6d+DJYc/iz65Gxq0sfRSLLI8xGiO/G"
    "TptG/LtsKhp/xOeB11EGSRiX0tm7J+fC4Yn7XcD5AUBd02S7GBrr5u+/eny5ucE+UKjfW6MF"
    "qta9ePyp3Ue47+2j0719r78KwJrTiz6H+lr95MCnHR2GIfjdD8cv3LiVeG2lA+bUZH3b08fi"
    "M7/JmQV52lxe+JGZjbzD3OdQX2v74MD+xrd2vlDtXNs1HCuzyIOKSgYACAG+EUr0M/NNAKiq"
    "CurAYo1hmMlI5PYMM4t/ATcGfRMjZzsD8UQGi3fMwqJw5tx89o1D13qZ+YdSbVUYectzC6n5"
    "Tb0/pUotiicyGoDYg2BFFT6s+AdIs2wC9lyU2gAAAABJRU5ErkJggg==")
getsortData = sort.GetData
getsortImage = sort.GetImage
getsortBitmap = sort.GetBitmap

#----------------------------------------------------------------------
start_fit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKLSURBVFiF7Za7axRRFMZ/5z7mETTZTXwgKGKpFiJ2ARULFVTE0l4t7YSgoJ1WgqQQQUSs"
    "/AN8NWKjomCljYiIioKKSYzZTfY5M8diNyFqJtngIxD2wOHcufcM33e+uffcEVVlKc0sKXqX"
    "QJfAsiUgIjtExC4JARFZATwDLnX0gqr+VQcGgAxIgWML5UteJxSRjUAESNv5JebNDQD39x7a"
    "JQ/uPW5mWbZHVZ8sSgFgD5C0q8gW6WkYBcm959ez/Ud2J967r8D6PAVcDq9N1pMdvLDWhTaS"
    "wEUELiLwYSu6dvTt+VkeBTF9vQVZucZxZviEvHn1rvfD28+3RGRQVWu/AuVtQmcsSl8JCmWk"
    "UMYUJ7GFCrZYxRXr+GIdX2wQFJuE/QlRf0rUnxEWM9GwKhOVUalrWc7fOOnDyG811lybCyiP"
    "gBWLKgn1ZJJybYxSdYzSdOzAJ1pRegZEzl457lT1qIic+q3SXAKGmd2pKPWkQj2ptKWOCV1M"
    "2IwJfEzYjAjd9Li95mMCFxO4WDZtX8XOg9t4ePv5aeBihwRkzoVGUqOR1KjZqRboLMCw2QKd"
    "GfuI0EX68v4XfXTnhQLnOlYAM3Mi5rRm0qCZNLBmqq1I1AJuVU3kY7yPdPRNTa+efpSq6rCq"
    "Xu6UgEkbyMenmQo/KyGzHwUgA2lgpISzAd4GFNb2sGFLH/VxozeHXjXTTO8CQ3Mi5fSBQTF8"
    "NpYxY/lmLONi+S6WCbFMiKEkhrIYJsUwJYaKGKoi1ESoi5AeOD+Q9q7zVevkGRDnds5/0Io3"
    "A2nPahrG8h5YPV9+3if4E7MAlTGmyNinqiPzJf+L63gE+ETGYVV9vVBy7mX0v2x5/hF1CXQJ"
    "dAksxn4AnNTsVlajiGEAAAAASUVORK5CYII=")
getstart_fitData = start_fit.GetData
getstart_fitImage = start_fit.GetImage
getstart_fitBitmap = start_fit.GetBitmap

#----------------------------------------------------------------------
stop_fit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAYbSURBVFiFxZd7bJXlHcc/z3s557QU1EGFFcZeatWS8A8TohKdt0HnLuiWGKMZBfxDg4hu"
    "cWDEltscYwsxWxgxoZMVCrWt0ckKhGEKAtsoFy9lizYr0/VyKox52tPbub7Pb3+05/Ce9vQy"
    "R+KbfJM3z/vL8/0+39/v+T3vo0SEL/MxJhKklFqrlIoppVyllJ4AXMsw3lFK5Y07uYiMCeBF"
    "x3Hc1uZmiUejkojFxsVAT4+ULluWNJU6AUwaa341VgqUUusdx/nZ2ZMnjbx4nPCRIximibIs"
    "DNPENE2MISjPu+U4GPPmsXzFCrd6//4/uyLfEZGBbBzWGOQvOY6z5ezJk8akSIRPysogGsW0"
    "7TQsz7vp8119/+ADAtEolZWVJnBX9f79h5RS380mIqsApVSZ4zibz5w4YeT099P8/PNIJIJp"
    "24jWGdAeiOsOwraJHDpEjgiVlZWmiNz9enV1vVLqeyISGVOAUqrccZxNZ95918jp7eXC008j"
    "AwNYPl920lEEidb0HzxIrtbs2bPHFK3vqampqVdKfd8rwhpGvsFxnI2Nx48b/p4ezq9cifT3"
    "p1euXTcN8SA9PkyMqTX99fXkAnurqkwRube2tvaPQyKiGQKUUhsdx9nQePy44e/u5vSjj6IH"
    "BjBte0KrTcMraCgd/QcOMEmEqkER99XV1R1QSj0kIlFriHzV7NmzN5w+dsywQyFOLF2K29c3"
    "SJ5a6Tj2j5eW3rffJk+Effv2mSLyQE1dXQ3wsBIRlFJv7dy27eHljz2mDs+fTzIczqj24bBG"
    "G/PuhFHipzz+OH0FBUwtKNAiYqZSoAJ+P5HOTuKhEEDGiiZqv/bUiYxSJ/G2NnyOA6AyasBQ"
    "6moxmiaT5xZjXXcdvX/7O8lolJyvzcJ/43QMy8KwLEzLgkiERGcn+HwEioowbAu3vQOJxRAR"
    "zDlzwLIQ08T9/HMkFsNNJjE9XFn7wMK6Gq6/7TbioS4CMwto/PaDfH31ar76wx9kxPU0NtK+"
    "Yyc3//oV7Px8ANxwmM9+8UuSwSDTytYjrpuOj9TWDQrwdN8Rh5ERCPCVRYvoa2mhubycf/x8"
    "K1g2zZs2c/r+B4i0tpEIh3lv6UO0bNrMrDWrsfPzaXnuJ1x8Zg3mlClMLf0RbjQKQLTpAp+t"
    "XoNSCmvePHQymcE3wgEdjfJxWTk3r1vLN6r2kgiH6b/4DN3nzhHp6MCNRjCTeXR/2IRp2+QU"
    "FhK7dInQqVNYtk2sI4jfcUjE4wD4b72FG1/eAobBwPn3yL3hBrynzwgH/DNmYAQCvL9iJe+X"
    "LscMBLjpx89lBomQjMVIRKP0f/IpvmnTwO/HVQp7+nSiwU6SsRgA8cv/5j97q2h7ahXho0cH"
    "HfCkYIQDia4Qhc8+C6K50nAMw+cj9Je/Dg/DTSTQrkvb7yu5fuEC5h+sB+1i2BaXql8nMZSC"
    "xOXLhI78CWtoi7qemsieglicU3fdTf799zF57lw+fPIpOt/6Q/p76+9ew8zNHTRCa4JvvEGk"
    "vZ38e76J4ffTc/YsfU0XsHNz6dxVQTwYJBmLpVu5m0iM7QBA/MoVgrV12T7R+truEWOhxka6"
    "z53D8DQe0ZrW3+5MN6BUz9DJZEYNpASIFgGlEIY6xP/4ZBxGw88DTzvXWqccELhahPELH30k"
    "Uxcs4KYnnvjiv6kiuPE4yVgsA4kh2DNnMqu0lI+bmgASXge276ioePCWOXPyVu3aZQDyz927"
    "1RdxwuuGF7mFhSysquLT1lZKHnlEAy+kBYjIeaXUkjXr1x8FromIlBuiNXlFRSx6803+1d7O"
    "HYsX63A4vFZEfuN1ABE5c81FAHlFRdx7+DCt7e3cWVKiw+HwCyLySup7xi641iImFxfzrYYG"
    "2jo6uLOkRHd3d78oItu9MSO24bUSMbm4mMUNDbQFg9wxSP6SiPxqeFzWPvD/ikiRtweDqZWX"
    "i8i2bLHjXUxuN+Dojq1b81atW2f0trRMgB4CM2bQevEity9Zoru6ujaKyMujcox3OU2JeHLZ"
    "skm3FhYqYxwPtAgDkYjaXlEhXV1dm0Vky5jzT+R2rJRaAPwU8DGxRinAOyLy6rhzf9nX8/8C"
    "0gOBIUzqXJcAAAAASUVORK5CYII=")
getstop_fitData = stop_fit.GetData
getstop_fitImage = stop_fit.GetImage
getstop_fitBitmap = stop_fit.GetBitmap

#----------------------------------------------------------------------
zoom = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAYAAAB/E6/TAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AASRSURBVEiJrdV7bFN1FAfw77m9belza7dubCzbeEhXnOPheCkQIKBI0DiEGBP+EBLiCJGQ"
    "6B8mBA3RP0xMjH9gggmKUf8AE/E/iCFMJJixB4jBRTeRjQEFNtbe9ra9t/d1/IMulq0tm3CS"
    "k5P88rvnc899EjNjYhBRAMAWu92+MlARXOPzesKapsckSeqSk/J5AD8z86VJB5YImggR0Sv1"
    "jfXfNDc/XebxuAEANlGEaRgAANM0cWNoGH1/9H2tqtl9zCxPCyIin9vt+nLR4kXbZ9XVYuGS"
    "FYg0L0Z1bT385ZVIZTK4fesGosOD6L7wE1LJBHq6e0ejt6PbmfmXKUNut/uHFzZt3BoIVqDt"
    "9V2YPb8ZhsnQTWtSTadS6DxzAsMDV9DbfUkbHByKMPP1UpCYm2bbyudXbA1UVGL3/kMQHS7I"
    "ilEQMUyGDgda1u+A6A7CsthxPxY7QUTLmdkqBglEVNnQ0HCsrm4WXmx7EzockBUDSUUvXDM6"
    "5IyOZEZHdWQtPIEaLFvW2ioItO9RE728oDniDbesQHnNvMKTGBYM04Ju8qQ6c8mrUBJ3UVVd"
    "/TaAz4pCoigu83o9CNVHJiNG4eb51XJWguwu+Mv8jUTkYmalIBQMBlYDgKOsBklFf+QEhmnB"
    "mvDqOcvrEAgMCABaAHQVhLw+7zzBJsIQfVAz+pSb54fDV4VAsAIAFhSFFEWNWqYxOx6XwKJ7"
    "ys3zQ8/EICeTADBUbI8QG4v9CgD3792ErOhIZ01oxtQRAMjGbyI2NsYALheFstnsxYySRXr0"
    "xrSaj4epJmBlU5CTqXvMnCgKATh9/do1Mzl4EXp6bNpQrO80FDWLkZGR46X2Ccx8vf+vgQNS"
    "PI6xKz8CxV/uSZG+dQXq6DX0dPXENE07UBICAMuyPunt6f0tm7yDe93fwsjESwvMkAc7Ees7"
    "hXhcAizT43fZPycib7FD8r/ejaGqUEfr0tbZXr8P5eENcFXNh+gq+6+/qUNLRBHvPwtNiiKr"
    "qlhc68SuZ5wgh4e3fHiy8+pwbHWhb95D/yMicoh28YNIpOm9cFNYIAJIdMLhq4ahyjAVCQAj"
    "kZAhCkBbg4LNjQJc/iCcviCGJNPaePD7o7dj6bdKQnngQlEU2wPBwKqyMn/Y7/fbVVVFMimP"
    "SHGpS1VVbd9K72vtS/1w+oIP5bmBmNX20cm9qm4eye8pFr4F/DuAPTnUBmAegBFmjufW7H03"
    "pYS2gF0k2JCf65pCwsc71x8mogFm7igJTUBNAP0T1nQi2hTpSXTsXm6zTcT2bGyy9d8aO0VE"
    "Lcw8MCWoxAmcF23UPqdcOrIhMhn7dOcq5/CodIGIwswcF/4vBACGyUcPdVpf9EclS0snkJ+W"
    "IuO7/S+FWueGOojIXvBhmE4QkfBUAOe/2jzjuVBlBY0/FDNy9U6aeMPB48ceayIAYGbr7zg2"
    "v3NWjWbkB9Po6QS0zIOs9Qu0tqXhjceGcliy+y5Wv38upWjjSO4Snu760zxz+Z/DYOYnlgDW"
    "7F0EvW9PkPvfncvtq2ZmAexgZjxRKIdt2zKHUs/WiFcBhMfX/wXbglYpYTSl+AAAAABJRU5E"
    "rkJggg==")
getzoomData = zoom.GetData
getzoomImage = zoom.GetImage
getzoomBitmap = zoom.GetBitmap

