name: genx
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - wxpython
  - matplotlib
  - platformdirs
  - h5py
  - scipy
  - psutil
  - pymysql
  - numba
  - cudatoolkit
  - vtk
