name: genx
adopt-info: genx
summary: GenX 3 - Reflectometry and surface diffraction refinement
description: |
  GenX is a versatile program using the differential evolution algorithm for fitting, primarily, X-ray and neutron reflectivity data, 
  lately also surface x-ray diffraction data. The differential evolution algorithm is a robust optimization method which avoids local minima 
  but at the same time is highly effective. GenX is written in python and uses the wxpython package for the Graphical User Interface (GUI). 
  A model to fit is defined either through a GUI plug-in or via a python script. The possibility to script everything makes it easy to develop completely new fitting model. 
  Clearly, GenX is extremely modular, making it possible to extend the program with models and plug-ins for most fitting problems. 
  
  At the present, GenX is shipped with models for x-ray and neutron specular reflectivity, off-specular x-ray reflectivity and surface x-ray diffraction. 
  A detailed description has been published in https://doi.org/10.1107/S1600576722006653 .
  
  Feedback and Help:
  You can find a manual with examples at https://aglavic.github.io/genx/doc/, for reflectometry a good start is with the SimpleReflectivity guide
  https://aglavic.github.io/genx/doc/tutorials/simple_reflectivity.html and our Tutorial Videos
  https://aglavic.github.io/genx/doc/tutorials/neutron_fit.html.
  
  Naturally a program does not become better if I do not get feedback from you! 
  If you found a bug or want to have something included in the program submit a ticket on Github at https://github.com/aglavic/genx/issues/ .
base: core24
confinement: strict
grade: stable

platforms:
  amd64:

parts:
  genx:
    plugin: python
    source: ./genx
    python-packages:
      - wheel
      - numpy
      - numba
      - bumps
      - vtk
      - pymysql
      - requests
      - pint
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxPython-4.2.2-cp312-cp312-linux_x86_64.whl
      - svgwrite
    stage-packages:
      - python3-minimal
      - python3.12-minimal
      - python3-wxgtk4.0
      - libsdl2-2.0-0
      - libglx-mesa0
      - libcolord2
      - libdconf1
      - libicu74
      - libwxgtk3.2-1t64
    override-pull: |
      craftctl default
      mkdir repo
      cd repo
      git clone --bare https://github.com/aglavic/genx.git .
      snapcraftctl set-version $(git describe --tags)
      cd ..
      rm -rf repo 
 


apps:
  genx:
    command: bin/genx
    extensions: [gnome]
    plugs: [desktop, wayland, x11, unity7, audio-playback, desktop-legacy, network, home, gsettings, opengl, mount-observe]
    environment:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      PYTHONPATH: $SNAP/lib/python3.12/site-packages

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  shared-memory:
    private: true
