#----------------------------------------------------------------------
# This file was generated by exportimages.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAJTSURBVDiNrZQ9TBRBFMf/b3Z25oA7PuQOj08JnhI0tlpZGBJt7axNLCi0sLHH2FsZTays"
    "tTA22FJa2UjQQECICDkk4fPY3dt9z4K9dfnYC5f4JptsZnZ++3/zf29IRPA/Q2ctENHw6PXi"
    "h96BQlkpBVIaYObNXzsLy3PV+yJSawlYrnRNP3k7eXNwrAhrLKzJwRqLLzMLQy8ff3oI4FWL"
    "CnG50OfA8w8hwhARiAhGJoq6rd3caDlliRiefwgWgUASoB94aHbqmUAGw/O9BPQPGADMzYFE"
    "1FMo6Sll6JJSCgQgCjB6lG4ayAg5wsFecHvkau8bxN/W9utf/6ztvBMRj0QEnYPq261H+Ymu"
    "UpsyroHrWnTk29BzsSMxw5ocTPx+sBVBKw3jWrjaYn1xJ3j97PPsynz1riaiSuWeU8yP1JU2"
    "DlxDsMaBcus4qZBjle0XcrDGxI9F36VhUxrqHG+krJWGYuZjgJNmpJ0+a045oFOmiMgpVSJ8"
    "DMwZ8Cg2SgOxmFT4gQcRjjefTyVHoTSAi5vzvD02qfpsgRJoUA/OBjVGam5jeRdb6/srAEAi"
    "AiIaz5fxnBSVkzoMcWXyhduvHZ24a00OUc3B+6erq7bD+UmkoEDgEN+rq/vTIvJbx2f3A8CD"
    "dNqdg2oWQH8YhZBU+wV7Go6VmepSbaqlTklHxFHSNfXAbdYo5wMeZXFUVmEQgZsQVSaAZcPf"
    "O30NbG/4zIEsZe2jrBubLF3rHqCPpQnVTfFvozp4c47Xd9fkjohstwQEACJyAFQANOopEMlW"
    "BwB/AfBKw8xrzH79AAAAAElFTkSuQmCC")
getaddData = add.GetData
getaddImage = add.GetImage
getaddBitmap = add.GetBitmap

#----------------------------------------------------------------------
change_name = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAIpSURBVDiNzZQxaBRBFIa/2duZzc7GIhglkFIUbSxELVKIrYUgQSNGLASbINhqFKKiEAuN"
    "TQqLNIIoKLEQRCQBDenCFZaBgIVJ2MMYyd1eLre3t/sscheMwShHBD8YmGL45ue9eaNEhJ3E"
    "2VHbvxAq4BbQB7wHUuAU8EZEhloRusAEEANDQA64C0y3nLDZFKXULGCSZ72XUtc/5nh+rM+M"
    "PQERpof3JI6+6Ojga+74wPM/JWziAyYtLZzGBNez2FJ70bdsLvAyWV7oxvMfi/E/AX8t7AKc"
    "LCqgtAVjQdt7vOobJ0mQmgVt10++u+alfudZyQX78Kx1XDvv+Ltec6g3dLdcERUQ7YO2eYw9"
    "Wq2WLqeul3e9dqQhXCsXO92kPoa2syq2JjP2oMTFB7mZscNbhVkNqdaQanFcaYvy7G3HbT8n"
    "cYQyQaM2a0vEa10UOiq13aUDyvNvirH94trzW4VNBJFaZZCkMqFyxaui7UbClcU52+aZt0p/"
    "O8KqdWmWwwTd2z7sYFgmgUlJk36pFpEoBKCtMj8gUaGHUjjqVQtWyuEjiUKIFtXPCYu/NGkd"
    "h0EyZjaFj5YjcUtkOuipxP4dR9srGEtd202j9x1YkYzPAlMOfAGw9yWvhBGBKRR5gNWMp5Im"
    "IxKvdFAO92el8IaUwinK4RxAJ3ACWGpITwJ7RYRWFsBDoA58BD409qOtChUQALGI1AGUUi7Q"
    "JiLl7Rr2OzZmeaf4/z/YH2geNogNOudbAAAAAElFTkSuQmCC")
getchange_nameData = change_name.GetData
getchange_nameImage = change_name.GetImage
getchange_nameBitmap = change_name.GetBitmap

#----------------------------------------------------------------------
custom_parameter = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAOLSURBVDiNrZRdaFtlGMf/z8lJzjlpZpo0sbFfpK32A9oNpR0apExBNpk48WYKtsJkUPBC"
    "vHH4xUC3XfjBLqaosHkjU5wiRkEnaAdaqKxbrZtoV93cYtv12CY5ab7Oyfl4vDAJTdYOL3zg"
    "4X3fP+f/e/+8vOclZsb/WeJGIhHdCsADwFX+xrWuK2sCMMPMzk2BgXDL49tiu45G2qKQJQ9J"
    "kodkSRJkyUOK7CFZklxeRaJV9Trin374GoBDmwKJSGzpGnxp5+iLzYrsgSKJ5XbXjf/Of/5p"
    "+ikieo+ZVzYE+ppaXhi4f/QOLW/AsBwYpgjDdMMw7fLcrtGePnAkupC4dhzAnhuAROQPdQ2N"
    "SaEet5bVYZRsGCVx3ei+QVN8Idy9Y1esMdA0oqWT39cAlUDr0cjQY11aTq8myGg5rFw+lxcF"
    "OKJAjuiC0zs47Ive3u+uJN69dzx0dvK7Y0R0FzPbYjldNNx33wOyP0JFw4JesqGXRMx/89aV"
    "5fmpJwEUAFgArNmO3o/2v3xia4NXhlGyoUgiHhl9pveDt195HsAhAQCUYMc7rcN72yppmRkr"
    "iTkz8/e1k8w8ycwzzHyBmX/NJJef/fbz95NazoCW06HldHT0b5ci7d37iCgsuGVfLNi1fUiU"
    "fTXXZ2H640tFbenV+mtVzGkTc+cmzi4tLUHL6tV+aOy5ztvau48L7obg4eatu0M1ptRfMNbU"
    "L5jZrAcCgKZePXJh6rSWzumoJIXkh+xrHBAcq3Qs+ftkdr1BCbZD2hLeQ0TKRsCGUPRgU8+O"
    "Ri2rI11OOPfLrJVJrXwi6Jnlz1bnzpy3S4UaU3tsrE/2R16vh3m8/pFAd+zOnClUzzCd0zEZ"
    "f/ePlJo4KABAIZXYtzh9anG90RvscPmaex4mohEi2kZEw0R0r2dL+M3mgZ1NjsPIF01oWR3z"
    "M2fya6nlN5jZEAHAscw/vU0d8WJ6cVwJtArVlPc80e4Nd8ZJEAXBJQrkcosNoU4PCa7qxqZp"
    "4up0/LeCpp4AAKo8X0Qk39I2ONPz4IH+jc5ts7o+++WqevGrR83i2g8AUE3DzLqxph5OXf4x"
    "u7m9tmwjj/SVqfMVWA0QAPSMelK9+PWsY5X+E3Bh+tRCIZkYX69R/Yvtcst9/rbBCV+kV2HH"
    "dtixHHYch9l22LG5rDHbNnLqpdOF1ML+mwIBgIg6AXhR/n/LbdatLWYu1Hv/ATPfytRdigbo"
    "AAAAAElFTkSuQmCC")
getcustom_parameterData = custom_parameter.GetData
getcustom_parameterImage = custom_parameter.GetImage
getcustom_parameterBitmap = custom_parameter.GetBitmap

#----------------------------------------------------------------------
custom_parameters = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAOLSURBVDiNrZRdaFtlGMf/z8lJzjlpZpo0sbFfpK32A9oNpR0apExBNpk48WYKtsJkUPBC"
    "vHH4xUC3XfjBLqaosHkjU5wiRkEnaAdaqKxbrZtoV93cYtv12CY5ab7Oyfl4vDAJTdYOL3zg"
    "4X3fP+f/e/+8vOclZsb/WeJGIhHdCsADwFX+xrWuK2sCMMPMzk2BgXDL49tiu45G2qKQJQ9J"
    "kodkSRJkyUOK7CFZklxeRaJV9Trin374GoBDmwKJSGzpGnxp5+iLzYrsgSKJ5XbXjf/Of/5p"
    "+ikieo+ZVzYE+ppaXhi4f/QOLW/AsBwYpgjDdMMw7fLcrtGePnAkupC4dhzAnhuAROQPdQ2N"
    "SaEet5bVYZRsGCVx3ei+QVN8Idy9Y1esMdA0oqWT39cAlUDr0cjQY11aTq8myGg5rFw+lxcF"
    "OKJAjuiC0zs47Ive3u+uJN69dzx0dvK7Y0R0FzPbYjldNNx33wOyP0JFw4JesqGXRMx/89aV"
    "5fmpJwEUAFgArNmO3o/2v3xia4NXhlGyoUgiHhl9pveDt195HsAhAQCUYMc7rcN72yppmRkr"
    "iTkz8/e1k8w8ycwzzHyBmX/NJJef/fbz95NazoCW06HldHT0b5ci7d37iCgsuGVfLNi1fUiU"
    "fTXXZ2H640tFbenV+mtVzGkTc+cmzi4tLUHL6tV+aOy5ztvau48L7obg4eatu0M1ptRfMNbU"
    "L5jZrAcCgKZePXJh6rSWzumoJIXkh+xrHBAcq3Qs+ftkdr1BCbZD2hLeQ0TKRsCGUPRgU8+O"
    "Ri2rI11OOPfLrJVJrXwi6Jnlz1bnzpy3S4UaU3tsrE/2R16vh3m8/pFAd+zOnClUzzCd0zEZ"
    "f/ePlJo4KABAIZXYtzh9anG90RvscPmaex4mohEi2kZEw0R0r2dL+M3mgZ1NjsPIF01oWR3z"
    "M2fya6nlN5jZEAHAscw/vU0d8WJ6cVwJtArVlPc80e4Nd8ZJEAXBJQrkcosNoU4PCa7qxqZp"
    "4up0/LeCpp4AAKo8X0Qk39I2ONPz4IH+jc5ts7o+++WqevGrR83i2g8AUE3DzLqxph5OXf4x"
    "u7m9tmwjj/SVqfMVWA0QAPSMelK9+PWsY5X+E3Bh+tRCIZkYX69R/Yvtcst9/rbBCV+kV2HH"
    "dtixHHYch9l22LG5rDHbNnLqpdOF1ML+mwIBgIg6AXhR/n/LbdatLWYu1Hv/ATPfytRdigbo"
    "AAAAAElFTkSuQmCC")
getcustom_parametersData = custom_parameters.GetData
getcustom_parametersImage = custom_parameters.GetImage
getcustom_parametersBitmap = custom_parameters.GetBitmap

#----------------------------------------------------------------------
delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMbSURBVDiNpZXPa1xVFMc/Z957904yNj860yYvTYb+AMGiIZLZaCHQv0BKCm5KMQVBN+pO"
    "oi5EpULXroJQF1lIFtWm7kJtQdoiSsWk1CDoOONgFs0vTedH3485LsxM3nSCFjxwFpdz3+dy"
    "zv3e7xNV5fEQEaOqQVfhSfaoajsBM5LJLDyby1XyfX33ej1vMllXVYwx48cOHVqePH68ks/l"
    "vgTSHYwEzA739Nycm5pq/HTunP5w/rxODA2Vej2v0Nrjed7ExJEjpT8uXdLG3Jx+PTsb5LPZ"
    "W0BPa4+oKiJiD1t7/b2TJwunfN861uJaS+A4XFhaKv+8tTUdhmH8zPDw1S9mZsYG+/txrcU1"
    "hlvFYnjh8uW7v29snFbVuqgqvrULb+XzL53K5Yy7C+uA3rhRbjabqc/Pnh0d7Otr11xjcK3l"
    "m2Ixen1+/qvigwdnXBExT1v7wvOOY4JajWYUEUcRbhTRjCJca/lsairvGIONIoJqFWe31soX"
    "x8bcXCZTEBHjqmow6jibGzs7o4NRRDMMuz5wrIVmk0D1n3WyHoZUHz5ku1bbUtVAVBUjMjni"
    "ONcuZrP+QDq911Ky/d32kuNwjaEOvHzlytovm5tnakHwrbR0aEQKI6nU4kcDA35/Ov1EwLoI"
    "rywtrf26vT1dC8M7AJIUthEpjIgsXjxwwM8koPsBm57HzO3ba7/t7LRhAO5+Qg9qNbw43pvh"
    "7qySa/U8NI67X1CyZR8W3wH/qdZp/9Fyw3F4Y2VlrVSvd7ZsRCZ9uJaEtSLlOF26S15aw3F4"
    "8/79tfKjR3uX4ov8+D6MPw5LhmMMrjFdCmhBX1tdXSlVq+OuiJgTcPDfYBEQBgEmDNuCb2Uc"
    "RXjG0AuDImJSqhr8BXeWYV+7agAfQvkDqFRVCRsNgmq1I79bX4/+DILv28IWEXsQrr8KhefA"
    "JmEfQ7kM00A8CldnYaw3cWmrrht+0mjcXY/j06pa77CvLNx8GxrzoJ+CnoCSB3v2BRPHoDQH"
    "Og/6LgRZ6LCvLoPNwcJRqAzBPQ+6DRbGD8PyUahkoctgO15KK/7PL+BvZw3/vhoZJLAAAAAA"
    "SUVORK5CYII=")
getdeleteData = delete.GetData
getdeleteImage = delete.GetImage
getdeleteBitmap = delete.GetBitmap

#----------------------------------------------------------------------
insert_layer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKLSURBVDiNtZPPaxNBFMe/M7ObndnEJK0t1rS1qdXWXyBt8aRULHrpQehRT4IH/wURihf9"
    "A7zUo+hBEUEovQiCIhZEQQ+KlCKIWrSxtsZmk91sdneeh8RUtBuk1AfDe2/mzefNm5nHiAhb"
    "KXxLaf8DyACYPSmcViY6N4wQHOCinlvUNefm+hwEIDjWKu7HwrfiA3Ykh7tXxzHZacOMTSvT"
    "YDILyCyYyoI1dQZo+J9Wq9Wpa7enjXwWuaO9LWAAwF0wW2Kx5uFlgcASAZKpGsZHtsPapsDs"
    "FPYN9MnpjvQB3ii7tegQ75cdXCkqrJwZhnP2MAoTA7g0+wzkOyC/VB86YsaKi7IfAZZozXy1"
    "HGL/hX60dSeglAUlbbxtTwB+CRAmim6I4o+1VZaVyA91YMoSyLQCfudmfvL68dHu3Z1Q0oYt"
    "bdy6OFdyni89hDDgBmz5xfzilFH06AOA8xtBmGL9mTYxAiHAfHbC893RiueASINII+S6sOB5"
    "dwQEKm7oAiizuE6RaTaYP2Y9GTqZ6lKWgpQKuYE2KJWELW0oaQOBCX+NYCUUdCD0zcuPHhtx"
    "JVrt/FTvmO4y2qowJUdCGqh4ZRARSGtorWHLJDI5G0olYMsk3zvc1R0L5FG9i8IwQMUrQxM1"
    "S9UNTUTrtiYEUYhYYETM0UHDjiK4brl+MqImXDeB9Tmn5Eaxd8gYS+44xGbTu9hOAADBGJww"
    "9qQyNmyZhJI2Vhao+PlN9aspDFAooqV3zr3YExJRBcD4Lz/dY5zrG6MbwnKbpc4/9ZZezxQP"
    "/r4vFthKqr5X/zaB/mvtn4FUi9zI54RGq/o1H7UahZsGlr9hdv5+OJfu5TlwkPYpdL5g5s+4"
    "2EfZrPwEltgwVtCuoJ0AAAAASUVORK5CYII=")
getinsert_layerData = insert_layer.GetData
getinsert_layerImage = insert_layer.GetImage
getinsert_layerBitmap = insert_layer.GetBitmap

#----------------------------------------------------------------------
insert_stack = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMISURBVDiNlZTPa11FFMc/Z+7cny8vza+apsRCbKFoBG1dNCi4KFXQhRbEav8Gu1Jw00Xp"
    "yrUbXboRpeBaFy2IC43ZFIwW1BA1TWISUlOS9+ved++d4+LdF2qaH3hgmHOH4XPm+z0zVxI4"
    "OX2Sm7HPMPuGgOeDF2CM7eW7cwCeBc/SzvThL7//ecO+cIpPvnqbNweC/XGgSBhCMookI0gy"
    "Wo0RJO7lJCM0NeHytY+O27GEoYNhFTJrIJ5fndRHjQ/94fmI51NPAsaOJUMW0MNxFTRt7EKk"
    "AmllRb8QrlC7vMPi98u8NDmIfzgyh8Y2EgsSKxI5JO4icYrEbZZ3lvP7axuLEo89eaXuezcj"
    "r0yOOqURKJ3zjRGMZzWO4sJ4HsazFEq70S5uyMjpmdmnLl6bOVJymVOsfsrFtyYJwxCcx+zX"
    "21x45Tr1JKReC/ni4w9/tGL8I1rSi/bWfV69OsT5S6MkUY04Stj8+1d2Gi2MEYwRxPiBTbfX"
    "76zMffmEF9UP9bDb2PS7eTrc7jRFVXHq6KYNd/e7zx/Ecagua+Zry3/csc/YheyN0YVwfICB"
    "x2QqbHUQsQlLYWDybEpa7SZOFVVHIKlcObM1aGt1/mmWrW83XGYn6rz8/gzH98KyEt6d85Bn"
    "a/hBQOBHTE15tDpNVBV1junXJmT17k4UhGDxI2+heM96sr/E+Q1oXzCMP+2II0MS+RSmQ7sj"
    "9CXHQzWmXx8njhLiqMba6sMBu5OR7ttVBTGQ513UOdQpzjnUOVwF1Ep6Py/KXO1fW1y/fAs3"
    "EBA/CtxsMajvcA6Qoiwqqa4C6H+LVMC0mzZEdf+XJyLBiefMDxPnzWkRBGDiee9YfTjZvTZF"
    "wy/W73VbQRBi1C/nb6/NHQisoAKcAgQ49+IH9tbYWeP3PEv47ZvuyuxnDy4BGZCr6qo9kAZo"
    "r9pSBT/RX++kbZxz5F0AllR1tw+HAvdEqQ7X/8i6KWlHlD1/q/8D/Gnxtvs5b3EGoMwp1++5"
    "eVXNHt10qId7Q0Q8YJKep4Wqruzd8y+HlGk4Ua24rgAAAABJRU5ErkJggg==")
getinsert_stackData = insert_stack.GetData
getinsert_stackImage = insert_stack.GetImage
getinsert_stackBitmap = insert_stack.GetBitmap

#----------------------------------------------------------------------
instrument = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAM+SURBVDiNrZNdbJNVGMd/513LurK1awsMurkxUg3bYJ2bHwHU+JEhGrZEg15oQgxeCMYF"
    "MRovyDRBvQMvZgLZhQZJTNxwwYtpRiKygB8MUDOpOJuWroOCbHtjW2jXNn37eNF1zn2ARp/k"
    "Sc75Pye/c87zgYjwX9xd42m+b+ODR6qrPQ0iwkzA5aLOW0fvv4EBtoeeePbn3pN+eeGlPWGX"
    "y71WA1BKrWpay8H9b9PeWK96nDb1gFKqiNtY5Z33fNTUumP96LUo9opaezabsOJZzZ5d27n2"
    "2ylE9yHhIeSZrYwXF3PXrV5XutKzq3HbvsTTe4/Ji+/0SW1dy2ERQQuM0j0S5IrLkb9VBIJh"
    "Pk+lxL/Yy5RSlrKV9a+a7dXW8O8xBj7tOhf69YedAJqIJCcnGYjfhOGLkJyCTIbx2/xWM5LX"
    "7ZIzmBg5Gfkj5H9ZRFIAJoCMwcj23RxPpal8eAP1liU8citai5eOJx89az3Yp3+fTkpXInH1"
    "/Exwdl4aPLz543HkbD/p+5vpXih3zet4o+cQ+t4OxoDyeZWf0wbLO3cT0X3I4Gck7r2b/bPj"
    "Tet4/ZMPmNR9SPtmTizYSnOFtlZO6758xfs/JtbipVNE8Dbw2pGuPMx/Gmls4N1/BPQ2cCD4"
    "XR6o+5CeQ+hN9Rw7/D4TBe1AJ+NAzUJAbW7Ch3+h+4sT6IV9NI7zlR20t21mWUE78xMBEQkv"
    "WP65goj4vxniEkDfl1C8BJ7a8te5VBpCYwwv1gHzgACjES4c7QdTEbS1/j02MEjyYoAPFwMq"
    "oGzTHexzlOAsiFMGK2JmHqtaBZLLT4+gyKGhRzVxmSuOFpksBmYLBY/G09FTZ869ZdpUxXu9"
    "2+gotyx257SZitFsbpTNjbJVPq+m11pZJcrm5galbH1up9IcVuyzYWljEaCRRowMGBnIpiGb"
    "gWxmRrMtteCw2+2mXA7t6xDJry4xGo4THIsRMCnKHCXYHSUsry2npnUNVY0VYrZmM0g2D1DT"
    "oGA4wlDAp18ITVyPxW8G1PoVbAjfwIhPcV5EcvOSrFTxMgsb1zh53F1urq1wlrqtpbalesp0"
    "9XLMuBLRk9/6x8YHReQygJoeuf/N/gQRVESSGeCRFwAAAABJRU5ErkJggg==")
getinstrumentData = instrument.GetData
getinstrumentImage = instrument.GetImage
getinstrumentBitmap = instrument.GetBitmap

#----------------------------------------------------------------------
move_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AALNSURBVDiNlZS9b5NXFMaf53742q9ffyWO7VgRTQAJhS5dUMfSoVLHdkMMFWP/hIK6dIK9"
    "WydGsoDCwsC3aIVEQ5sWKrU0AYaSBNwmTgk2fl/7HobXxBDsKBzpLkf3/M5znnt1KCLYGSRV"
    "EATVSMIZk7IZQEMgGkpZAPCdzZW41fxTRNo7a807tCTSsQq/dMWpEzYYKyhluwAVdUr3oue2"
    "1fjrFlrN7wAs7xVotQv3BdXDs5nxAyFAAAJlHOKtBjrNlccAUsMKRwFBZcS4fFe7XJIQD2Uc"
    "enYLSps2AP8+QCqhFt+j9Lr9lIf3GuJ7EHiOEqJG5T1hQSqQycQYMAgIkrNnIKGoqfRIJe+r"
    "kBBqDOQNtAEQ4VB1uwIJMQNCPyvJpBz+HrsCeyBJKiZI2dZHEkorD6A3rHD7lUkaJH9LAOR9"
    "t5MBRBGEgBDxoFJw1oDeWwBFkkG/T0dEuttAkgSw36ZzR01hKpC4U9Kp7IdQut9QIAKkrEY2"
    "nUO3UjtYm8gfzxZKzx4/+P3/jWdPrpJcEhFvEmtESFag3TGXrx1xxQ9EmbQz6aIW8RARaK0Q"
    "Bg71iTJmZ76aLuXc16uP7qnGk+U7G8AfAP7e6eFiHL/4odtq3lcmk3Pj+1PKBsmoBLLZNMaK"
    "Ier1Oj76+BNdrtSC/57+s7S1uXEWwKL0t8y2hyKyBeAcaf8F1ElAPnVj0wQIazRK+RDViXFM"
    "ViewsfoAty/P/XL3p0tnNtcbF1779xZwAI6vkHwpPo7DbvRZWD2kisUCqpUyJqtlbK4tY+Ha"
    "3N3b18+fidrt+TdhQ4F9tT+S/FZ8HKfT5vPygaOmXqvieeMhfrt5fuHnG/Ono6h9cSdsJLAP"
    "XSB56kUm0345Vfli3bXs8q+XFxZvXjgdRdFQGABw2MZ+M3IuN1vad/Abm0pNN9cefb+eeDb0"
    "U+8JCAAk6wAKAB6KSGe3u68AdHQilENlm/4AAAAASUVORK5CYII=")
getmove_downData = move_down.GetData
getmove_downImage = move_down.GetImage
getmove_downBitmap = move_down.GetBitmap

#----------------------------------------------------------------------
move_up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKuSURBVDiNlZRNTBNBFMf/b2e7211K+RIhEEEorWCKJiRyUAMkmohGYuJJuXvxwMmTV4OG"
    "ePRouBGuxsSvg4kJJBw8YDCExIMmIqFYoC0tlLazO88DrYGWLbrJXDbzfvN7b+Y9Ymac9BFR"
    "O4AmAMvMrKpuZuaqC0BXW/fFmUj/lc+mad4GQNX26yeYnatv65sKD47d7ImcNwKfZieXFt6D"
    "iN55mXoCiajf3xR+HgwNXbdb+oTd2ImrYw8uCCGeLs6/0YjoLTO75XGaB+yS1dz7oj48ckPU"
    "dYut5C5iG3H469tx7e7D/sHhO5NCGGNEJE40JKKhQEv0WW1o+LLZ0AFmRjKVguXXYdsmQl2d"
    "GL0/EfX5jSdf5j8QEb0+nL5+CFQjjMCo3Rp9HAyNDJRgYIaUCtuJDGr8ftiWHz2hs7h1byLq"
    "SGdqZXEucJroVZx590jKPp/dS5r2yAy2hl2Z3cnGv0l2ZekwZLP72EqkEd/cxuLCR/f3+tpu"
    "R0/0jNCNiZQd7CMi7YihlCqhQc4WMnGxn1y12cmPNw+M9+pmnQAYihmpzB6MTeDH3Mv12lpr"
    "pqHxVFrmczmpClvH1DD3S0lM78W+agB8utU4ANeJABAlS8dxkUimkYyvrcW+x6cBbAJQAHKl"
    "Ov4FMrMDwCkGk+azsmAwCECxmRhANpcH6aYDIMHM6fJLPfbZADAAVoCq6EtWDNdVomT+r0Am"
    "gjyuz4kIBO8B4AWEYnaK76aMCDBA/w0E2GF2K3hV5KoCGUwFcHkN+UAR5GnoNRyYwBJETEI/"
    "xCKw5qJKxp5AglIk82mfnssAB00AIg3KKQDElhfV05Ad+XM/trzi7KwbIB1EGkETGitHV65c"
    "BVAxuoDi9K34SURATYsesCO6MHRAEIMFNE0AQqj89obM7iwxsyyP/QMEi1MYTwiGzgAAAABJ"
    "RU5ErkJggg==")
getmove_upData = move_up.GetData
getmove_upImage = move_up.GetImage
getmove_upBitmap = move_up.GetBitmap

#----------------------------------------------------------------------
sample = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAKjSURBVDiNpZI9a1RBFIafMzP33t17N5vdXDduEpUNfhAVJWChIiiCjYWNjZUINvkDEbFT"
    "sRMrQQQrC/+CNjYigqCFpPADDCFBXTUbNTGbvdmPOxZ7Q7IhWb9eOPOeOcUz58yMAFLMcMJ3"
    "CdlQetWNBq3buV6pG9AuS9Vo7nOl8kSODHHj+kkuFXzcjYGA14OkcpDuRVK5dqRzSa3tlZrU"
    "r9y6f9MMZike294FBsBPJKWRwAXfR/wW4oP4GvEdxE8x4ofuUH+uaBYiWrEFJd2RNvoBIggC"
    "CDZxEBBFbIX5H/MtyeUyx/fk9f20I6Y7EkQEZQyiXbR2kSRXjsNSPW6+mylfMK1M6Xx86nKp"
    "ym9aTJQNPDJBih7fIxt49AQe2SBFJu1y78bYeSOxjVqNZbST+iPgQnUZC2Bt+yqSJaotUq83"
    "ItmW52C+t/DIdYy3yaCgFCiDiAGlQWmUNijjoLRBK5eoUV8uT0+dNof6GX9wdnaw68CikSBE"
    "/JXoA3/tPoR0H+fGb48bK1hrQboRbQu7NLeu786XtjHEzchKMUVp3zCPPY+ezYkKRIEYRDso"
    "5YFyQDzQBlEeyw37c+L1p1NmYCdjV68xvGsYtTkwRpSPmBBlQpQpJJ7kOmRqprHl4tidMZPP"
    "U9o/0g22okVEgdKC0iqJlcfR7N1TUGFfUPrtZ14rGy8SNzsqnXPEdf4KuAq166uJ/QOwDa0m"
    "na4HNzqBtQgmpyGXha0FcLoctwpdBdu4jmk2UTfvMvPiFW/mvvP+2zzPgzQDnsvu3l6GSkMM"
    "nzjKjsOjBMX+TmitVmXibSt+9nLhy/TH6XJ1qflCBkL2lueYtdZWNupERMR1OTCykzOFPKPF"
    "IoOeS+ZrhfLsNyY/fOLhx888tdYuAIi16+/h//QLBAXWl1dnDcIAAAAASUVORK5CYII=")
getsampleData = sample.GetData
getsampleImage = sample.GetImage
getsampleBitmap = sample.GetBitmap

