name: genx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - wxpython
  - matplotlib
  - platformdirs
  - h5py
  - scipy
  - psutil
  - pymysql
  - numba
  - cudatoolkit
  - vtk
  - pyinstaller
  - requests
  - pint
  - bumps<1.0.3
  - svgwrite
  - orsopy
  - docutils
