#----------------------------------------------------------------------
# This file was generated by exportimages.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

insert_layer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAd9J"
    "REFUOI2tUjtoFFEUPffNG2fnzczGnairrKk0K6ax0ELBQqtgkUa0EyzsA9aaylJEsAsKlglq"
    "46fQQjRBQSQiBpHELBg1IKxh434yOzvM3mthFlYc/BBPcy+cd859751LIoLNQG1K/T8MNAAQ"
    "0e5e/w9IRWSFxsq4cfYATrsa1i9HbAOYAsgNQW4B5BYAN4QyBbTJ6968O3tbD4con9iLfPaQ"
    "CEnOYPprAsklkE4TR3eFGCkXQf5OPHu9UNYpg393z1vv27AmDmPb9hCeCfDg8gvsHyoCloM0"
    "jli/rWLqwhNoW2U8AcA8Y2hMolKjZYGZUak1GxPXH71LldudX65N6ccfZBLAZL+IiOytJXt0"
    "S84KLI2Tx1r1U8IMFsZq0lmcXfpyjYjk8+LqDGUtUumQdfXgGX98IAyU7wcIBwfgmQC+CeBo"
    "A5tceK6PO1devsmMzslTkbxYdQTQXaDRApgZzAzfMCxDYNtGWDJhdvYCAYBOEoOZIRtiFobI"
    "j8rCiOO2ZBpENbm/9LC7jxQcpdru8Cjv6YmWX9Wr3z5y1bYdqVaiucw/6MeOEevSkfP6IpGC"
    "bwIs3Eufzk3Xjvf4v15fEUZzvY5O8nPafzRI1mXm03M+ZwaR5xTp2kpa6ee/A7ZRyy+qvKUl"
    "AAAAAElFTkSuQmCC")
getinsert_layerData = insert_layer.GetData
getinsert_layerImage = insert_layer.GetImage
getinsert_layerBitmap = insert_layer.GetBitmap

#----------------------------------------------------------------------
change_name = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAbhJ"
    "REFUOI3Fkz1rFGEUhZ93nJ3JMu9sGBBJp6KFFopWQsTSHyCIhWIR1EISIlrKIgFJQIRITLAI"
    "iNpoEU0h2ImFhV8oiq2Q/VDSGN1ZdHc2jjPHJitmIUXYwgOXyy3uw+FcrpFEP3L62gYMcBT4"
    "DXwEDgOfJb3fjIMdwDSwDIwD2zZlYS2DfUDWfnB8ePXhyKtfj8dPS0IS6Yu5hfTdnYnu3Fvd"
    "DLYCjtOoR4prhxRXb3D/VASguHpAzdrujQy4az0CyBpLGK+E8cM88ezVIozlzSomsQCkT8tj"
    "phCcxw8H8YNH7sGRC+46XGsFtRpowF4xXnizNbNnfkthEHkBLJywygujFMMZCqGLb2fTl9N3"
    "1wMAlMFq8606zXu0i7PyQvAsnH32M58/cs5J7Bn5wbDxSqgVDHUBWS8nF5edNPmkNCmZ1rfX"
    "nclou1z7PPOCi/JLtxzPvjGe/RviEpD/C7BT+mpgAjCQkbXjSM0vRnF9F43KlOIaeVwfcIwx"
    "O4FjACcX2fs94TopywBFnzlEGVgMJvUBMUqauPqxckmNallxpWOAa8AQUAH2A08k3d7obL0y"
    "//2Z+gb8Aa/NxiHXN1trAAAAAElFTkSuQmCC")
getchange_nameData = change_name.GetData
getchange_nameImage = change_name.GetImage
getchange_nameBitmap = change_name.GetBitmap

#----------------------------------------------------------------------
move_up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfpJ"
    "REFUOI2Nk8trE1EYxc93ZzJpXpPiA8VHEltEktb3g1SM6M6FiP4D/g3ixoVoBRciLsQ/w1r3"
    "IogbcSEUXCkoIe2iVKpJJ2mek5l7XHSINZlUv829XM758Z373SskMa5EZB+ASQCrJJthGnOc"
    "OZraNZsrzL2w7fShTrv+SEQWSPr/BRCRs5O54rNjl29fnZqaxvLnN/c3qz98EXk9DBkBiMil"
    "ZKb4NJEtXay2Tex3FWaL12eiVmT+07tFJSKLJL1QgEQmrtnTVx7b2eI5FduNarXGckXBPpGX"
    "U6VbBcuKPvz4fkGJyCuS/QFARAxYyZvp7Nx8Kls8bsb3gF6fHrX8rDn4Xl5m6mRezpRu5Kn9"
    "Bx86LyWAuEISIrEjZiJxR8zYeWVYfnzv0Uzy8IUDKmqbhhKkYqJVo7zm1r5Veu26ajacJWd9"
    "/Xmn41SCCN0Vr9W9B6APoBBNH3xC7WWUYUBrDWfDUd21la/NytLdVmvjC3K5CLp1dxCBpAbQ"
    "DeJ0AaUBAiQEgK81em6frVbbDaYwmIQKm+JfCwACILUCOKIPAwAgt2z/rjAAMezegTXuJepg"
    "ExwAIAXbc+3QAaAhoGzd4x9XqDa0A9/dpNtYhfY6gCitew3l95oA3JEOZPg7i0gcZuq0YUVm"
    "SGPCABVFEqRX8TveW7Lxa7v+N7Sc4MT0MmMHAAAAAElFTkSuQmCC")
getmove_upData = move_up.GetData
getmove_upImage = move_up.GetImage
getmove_upBitmap = move_up.GetBitmap

#----------------------------------------------------------------------
insert_stack = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkBJ"
    "REFUOI2lUz1rFFEUPffNezOZNzOb7Ec0RPADFTSNQgpjYTAi2FtZCAqCnUXQ0kpjEazsbQQL"
    "mxR+/ACDRiGEgBIwKyGu2Q2GNWbdzc5udnb2PotEXMkEC29zLhzueffjPDLG4H+CLhzBtRNZ"
    "XFUWxC5WuSDlgWwN2B5IeYCtQbaHNjn86cvaUzmUw/XJizifKC8ikJ8B+TlQsB/kD+zgdn77"
    "0ZSUtgVrz/64A9OsAJYNSBuwnB3czm2KLfn5B4ozRcRKQCarNADnO0h3QG4LpDcBvYFYfYvz"
    "S4WifBsNr8/O95UMaPcOABjDlMtUU71ph8CERlWEPS7aParOjbh/XersodHB4cuH95qiVZ7G"
    "rckIuf4MPB3gyb1i6sDhm+gLXLx7+XhUNiulUm114SSRSO4gLFiR6RO1ugVmRrtdMYsf3se6"
    "R/HKcr4kz1izy6ersxW764wdAxQaZHekIwqR7WzWRxzDDDYMEa7G6fJUs0OKs6K2RuMjmJ4Y"
    "w2j3qw/yhIVzAVKZAL4fIJPthacD+DqAIzUUufBcH88fzoeSE4xYFQR4W2gZQHaAWh1gZjAz"
    "fM2wNIGVQu+gI+XiOl5NvIFv0R8/fBQ4mAbSrWgLzAyzU8yGYcw2smHUm2GDkv7CwCnrSuYY"
    "3SEBRwi4xy85R30dwNMBNvIo//zKZaUcU15qzCUKdMe+Iev+2XF5l0jA1wEWX8Sv555tjP3m"
    "93BfwjkNYzOsohX97fx/CkShmV6Z4Rs6ixTHiCuleKmb/wWF6Ou7y8qAGQAAAABJRU5ErkJg"
    "gg==")
getinsert_stackData = insert_stack.GetData
getinsert_stackImage = insert_stack.GetImage
getinsert_stackBitmap = insert_stack.GetBitmap

#----------------------------------------------------------------------
instrument = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm5J"
    "REFUOI2FkV1I02EUxn/v332oW3PO/ChzTmWliEZpiIaZFVlGSApdRHgR0seFddHXRSxJEKKI"
    "uigTgi6iEAmSvDKLrFQQRBNbaQ5zaKLShqXTXPvX24VKS1APPHAOD+fhnOdBSomUEkBZ6tdC"
    "Vm7BxaLikquAsrSsL8ilK30zu9ZaTkzbUem42zRf9/SttKXYS5T8HHG84hgvH90h+1wFjwvz"
    "RAsrVHiUdYvFnn9+ck6vb33zzj3vDziVuZ+M5WWRbDRA8R4StBqcKwmY4tOvK9GZib19H/3t"
    "L5/fGB8dHtJ098nWsyfEB52O6JAQNFPTeFcS0KujNt/4p4DH1dHoGey6D4CUkpxtlNttnK6v"
    "RT1ygE4gbPnvhblU36riu9lMWbDhBKWgqb7AwFg3suwQzYB2idudR9XrBnxXKulZLvzfUF5G"
    "g9eJdHciS/bzDFAKcnC8amDa60QePczDVQW2Z3BqsA3pdSJd7fzZl09PSz0/vE7k+xbUVDul"
    "qwoAxtvXcHudyAc3kS+eLIh5nciay/QHv7UEJdhlKaVvwEVfYzNYN0L21n+ca5heKWVgeTIC"
    "CNmbhMOgYx2AD3L1MWSnWBcvRPAroIgvQ+G9ptC4NnThCK2BWVWZbWltrxaladTeO8gZk36F"
    "8LVhiMgkFEsySqRtsU9iRhPDyUs1dZoNRqJNevjs5XfnV0YtYZgyY7FYIxbOQ/UvIDCPVP0I"
    "1Y9U/RgNClEWc6woSsFh0GHq/0ZTv4cOwJARQ441gp2bTFhjDVjXW8wJqSkJccOzRs+EP3Rk"
    "fIaRockZ99jkVKNYdH/VEkIIIB6YkFKqwdxfQBSLyRzwp/EAAAAASUVORK5CYII=")
getinstrumentData = instrument.GetData
getinstrumentImage = instrument.GetImage
getinstrumentBitmap = instrument.GetBitmap

#----------------------------------------------------------------------
sample = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhhJ"
    "REFUOI2FkE9IlFEUxX/3fe/792Y+nRlHnRmp0CIVysDcREQQES4iaNMuilbZJog2tQ0qyJWL"
    "1rauZbQMN9XChZJii0yhJGOUNKxwZvzmtRizSWfqwOOe9x7n3HOvAGb4ELd9B009REAHiPZB"
    "B3t4qaq2Xrx8M6ovD/B4bJgrnsMuWFBbSJRFok4kmUOiHJLsRKIclSDLjfvpHp0JSe4Vb6Na"
    "wX4v1tKI2j417ooik9BJOZxVpwb3mfHQlSYuoByNeAblGZQXojzDZqx5PbNwVa9lT4/MH7/W"
    "gzQ3cJSQbglJR4ZUS0gqCkklfebHH4zo8s/1iZXZ52eV9psMIoCwqiD0PUzgYgIPLXG8Ulye"
    "0Odbp4YenZhq93UDreMjUUdtcclcjSfakKiTkpvm1uj7Id1uyLQGzcKXYLOIaIW4DuI5iKuR"
    "skvgeXS0ehkZ7OFSXzcPjc/eJYhCxAflI04C0QZxDDiGzYprZ98t3dH9x7g4do/uxgmqIDGO"
    "m0K5eRw3j3ILtarzXL/59IKOkjSa/g9smbjyGbD1j1gLJtzy/i3+y2R5R/y72OqP/3RvmGT7"
    "Wm9QrsCrSTbezvHBGFoG+ikc6SVImN0mlZ1xNjZivq2vu3LmJHetJZye48nXNTsvIsqE9B3t"
    "41xXjv6uPPs72jjQe5DCwkdWiqssLi2rxcVP7szkdOmZWGv5H0REgALwxVob1//9AoNomj/F"
    "iOesAAAAAElFTkSuQmCC")
getsampleData = sample.GetData
getsampleImage = sample.GetImage
getsampleBitmap = sample.GetBitmap

#----------------------------------------------------------------------
delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmVJ"
    "REFUOI2Vk01IVFEUx3/3fc17k08by5VMGqI4YxomKEktI1CCsEUrQfdFEVFEBK2rRdBmKLBN"
    "tGyb1kbEMsMRTfOLwUWBmwbGcWxq3vW922beNE6rDlwunP89555zz/2hlCJcgABOA0a1v6zp"
    "ZU0c8lcdaOxtapp7ODiYG2huXrV0/WSoRQwjfq69ffnZ6GhusKMjDTSFmlBKIYRoPBOLvXs6"
    "MNAXq6/HN02uz8xszu/sDAshvLMtLVOvx8cTrutSBK6mUsvT6+sXlFI/BCCS0einx4lEf2Nd"
    "HYbjYNo2vmVxbXZ2S9O0YGJkpLPedTHLWhG4kkotfMxk+nWg57Lr3u6ORGwVBCjfJwgCdKUY"
    "bm09dqmt7bglRMWvggBL0/CUik6trb01gK8fCoVvF2376BEp8T0PM9wdB+H7lHwfX0pMKQmk"
    "pFgs8iad/g6sCqUUlhDxLsOYvBeLJeuiUQzbrpQbtmQ6DobjEJgmN6anNz/v7AwVSqVtUZ4A"
    "lhDxpKZN3m9oSNphYE0S3ba5lU5vprPZoX3P2wYwqDIVBJT29qCq3LClQEo0zyM4OIDypYSf"
    "whIinoDJm5C0yoIeifwtvaolFYnwIJPZXNrdHdqXclsAeics3oEei8MmhPjnDcIkdzOZlcV8"
    "vtcAuvrgRG0wwIFSyGIRX8rKFMLpnHfd+GI+f0oDVuZh62dNsAc8gq0nsPFLSkqFAr/39igV"
    "CuTyed5nsxngS4WDBCw8B/UK1EtQPbBhQJsJ8W5YmyhrL3Rdden6UsjDIZg6YG4Mcp2wakAF"
    "JhPinbA8Brl2OARTLbL/jfMf1kVvNbeKwiEAAAAASUVORK5CYII=")
getdeleteData = delete.GetData
getdeleteImage = delete.GetImage
getdeleteBitmap = delete.GetBitmap

#----------------------------------------------------------------------
move_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAdZJ"
    "REFUOI2Fkrtrk1EYxp/nfJfcTJtL84UvJV5qqg206uAiDoKXxcXSP0AUFzeh/iMWioJQcNHB"
    "Ig51qjrUQVwyqohD2yhiL1DxGtrmPA6J0CRf6oGzPO/z/p73PRxKQvehlz5nfG/MkesBcGTo"
    "W+38sL+35iTtdHi7ASSdeK6ylDl28QwdV6ABJPPt48vlP+vvTkj6tdfv9sQDoOsxljlIGGMI"
    "QLKgF7dAscdrogAgJQgE1RpSINmMskYDwJa+d73ep9oPIAOwixmN6DcBATG69n+ARUd8K9gY"
    "xwJrti+AZJJkAoAPtnW25iaBRMwXkE5ydDTG4eHkvz633ew4ieycGx8s0bjyU0MFklayBIlc"
    "ZlA8Us3l0v684S42ftY3SV6V1HABQFLTjQ889A4Ed7LVy0cdJya1dMR8D2FxCGNnr4eHSvlw"
    "8fFsfePryj0A2x0r7Da+P2tsvr+29XbhQ9NuEyRoqLCYV7lUYJAfwIsnd+u114u31z+vzkuy"
    "QPRXnogXxx8VJqbGg2Ko45UyR8oF1J4/WKm9Wphe+/LpaUeDpJ4LYCQVVGuXbt7XrZklXZi8"
    "sRwE5clIb5TYhoSlysk3p89PreZLh6/09fUrtCFZz0ud2s/zF31iCKkX8usKAAAAAElFTkSu"
    "QmCC")
getmove_downData = move_down.GetData
getmove_downImage = move_down.GetImage
getmove_downBitmap = move_down.GetBitmap

#----------------------------------------------------------------------
add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfVJ"
    "REFUOI2Fkk9rE0EYxp/JzuzMpiG0kQSlAVFUrIfQYq1fQPTQmxfBiycPnkQ/geBJ734Cb4JS"
    "BfHuxaLiyX8UkYKCpWk0ljSbzM7O4yG7aZIGO7Ds8rzP+5t5nx1BEpPrRKP6pH76yHmlZBAU"
    "Ajjn7dZm++WXtz/uTHrlpCCEaFy/t3Jp9ebSnNERtDYwYYRHd19dFULcJ/n7vwAAlZlKUIr7"
    "XZCEpwdJzNaKBkAZwKEA2MQi7g0AzACJS6ZZBwAhRA1AMdOO2qQ/BvAk3ABQF0LkvW2SbVk5"
    "GTxbWC2uFMtKSakgA4nqmVDmI+TP4uX5OeLiUxkMPH+3497Z5fqaOHUl+Nm4ZuZNaKB1BJOF"
    "ZnQEHRqYTNNhVtPRwBcaPLjx4ptUEZRzCWLv92f2HAswHyPPw5Og9yhIqmGIqU8R97qZkWMB"
    "7r/Hay5NIV0faQ7x9Oj1umONB3YefnskNnGy+dl/namJkirC5KDqQqxYHgUQnZZlc6PllFII"
    "VYi9nXT31/c/bwRJCCGWAZSy/sULt+TDY0sFFSo9DPDT8+72+uOd2wC2Mt8OyY8SAEi+z3cf"
    "+c+wSX94iuwirZPcPPQmjq7EJRlger0wRdu1HcSjQpo6dNvWAtibNB84AckPs8cL7+IWzwUa"
    "AQDYDmxrw78m2Zz0/wPaZlK7M2tZEgAAAABJRU5ErkJggg==")
getaddData = add.GetData
getaddImage = add.GetImage
getaddBitmap = add.GetBitmap

#----------------------------------------------------------------------
custom_parameter = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAsVJ"
    "REFUOI2lU11IFFEYPXfmzrp/bra7rmu2+ddKprEU2A9FPQRhpSCCJQVRQb1FGEUPERVEBAW9"
    "JD1FBT30UD1FQQkVZCVF+JPRpqTlrpmOubuuMzu7M/P1YGNlvnWezoHvfPfe832XERH+B/xP"
    "wRjzlIZrL0qSZOOiKHDOmcRFxjkXOBdYLpcT375+cYyIxhZssKRy1aWWI5cP+/1+uBwS3A4b"
    "XHYJLocNbocEzkwcPbTLDqDZ8ggWsdldpcHw2u0zOoecUCAnFEwkFMjJ33w6Y6Jp94EtodKK"
    "+n9u4C5afiVQUx+aSKhQHTpUTYKq6chotlmdtUHVdNTUbfWWh++fY4x1EJHOAcDuCWwoWbt7"
    "82RKQyZHUDIiPj293icK+M5FwWBmrqDpwMl1Pp8XGU1H8/62NfGR4dMAznAAcPrLznsr1vsI"
    "QFrNYvjdk2+j/Z0t2kwi+itct+TwdO3Y27ZSdehwuwp59eqNexhj1wSnr3RPMNKw3nqKmctA"
    "HnzdYZkBgIjSXwd62qMf3muz+ajYsGP/8nBtXbuQ5wnscxVWOq3i5EhPSpGH2+fPezL26WZf"
    "1+OYFWhSMeBaXFQlaKnxq8lYb8oqLCiv8+QXV5+d38BdVHXRV11fKSdnJ/N5cECPD0VvC8rk"
    "lwfj/U+ek2n8WiYBwUjDJqc31GqZRW4rWRSKNGaZHXJChZxQ8OrRjXcTsYHLjIjA7e6lxZHG"
    "l8FIQ8gyjfc/HsmmJxUmiCITbXnByM6QIEoAgNRo//RI562DylT8LgcAPZOO5RevuOMLbzwu"
    "ORczAAjUbAthQRC+9z7sUqbid//axPRY9FT87b3uhU2/MfHx2diMPHTC0nObSEQ5l7/swtTQ"
    "m1tO3zInEQFkgkwDROYc/zHY+TSnJOcOYvO/s9MbagUT8kFGlkwjQ6ahmYaukZHNGrqmkaF3"
    "E1Haqv8J2xVNEQjv3kgAAAAASUVORK5CYII=")
getcustom_parameterData = custom_parameter.GetData
getcustom_parameterImage = custom_parameter.GetImage
getcustom_parameterBitmap = custom_parameter.GetBitmap

