# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file genx\windows_build\conda.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Build with pyinstaller
      run: |
        cd genx
        pyinstaller genx.spec
    - name: Download and Install Inno Setup installer
      run: |
        curl -L -o installer.exe http://files.jrsoftware.org/is/6/innosetup-6.1.2.exe
        ./installer.exe /verysilent /allusers /dir=inst
    - name: Build setup file
      run: |
        cd genx\windows_build
        python update_version.py
        iscc genx.iss
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: windows-dist
        path: |
          genx\windows_build\Output\GenX-*_win64_setup.exe
        
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-matplotlib python3-scipy alien rpm build-essential
    - name: Build binary package
      run: |
        cd genx
        python3 setup.py bdist
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-dist
        path: |
          genx/dist/*.deb
          genx/dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build-ubuntu
    
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ubuntu-dist
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: testrelease
