# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'What action to trigger'
        required: true
        default: 'minor_revision'
        type: choice
        options:
          - minor_revision
          - full_revision
          - only_documentation

jobs:
  build-documentation:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-matplotlib python3-scipy build-essential python3-setuptools python3-pip python3-sphinx
        pip3 install orsopy pint
    - name: Build html documentation
      run: |
        cd doc_source
        make html
    - name: Move files to doc location
      run: |
        rm -rf docs/doc/*
        mv doc_source/build/html/* docs/doc/
    - uses: stefanzweifel/git-auto-commit-action@v5
      name: Commit new documentation
      with:
        commit_message: Build documentation with Sphinx
        file_pattern: 'docs/doc/*'
        commit_user_email: artur.glavic@psi.ch
        commit_author: Artur Glavic <artur.glavic@psi.ch>
