# This is a basic workflow to help you get started with Actions

name: Pre-release Actions

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'What action to trigger'
        required: true
        default: 'minor_revision'
        type: choice
        options:
          - minor_revision
          - full_revision
          - only_documentation

jobs:
  perform_pre_release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-matplotlib python3-scipy build-essential python3-setuptools python3-pip python3-sphinx python3-h5py
        pip3 install orsopy pint
    # update version based on the last git release tag
    - name: Increment version minor
      if: ${{ (github.event.inputs.action == 'minor_revision') }}
      run: |
        cd genx
        RELEASE_TAG=$(git describe --abbrev=0 --tags)
        python3 -c "from genx.version import increment_version;increment_version(minor=True, current='$RELEASE_TAG'.lstrip('v'))"
        GENX_VERSION=$(python -c "from genx.version import __version__;print('v'+__version__)")
        echo "GENX_VERSION=$GENX_VERSION" >> "$GITHUB_ENV"
    - name: Increment version full
      if: ${{ (github.event.inputs.action == 'full_revision') }}
      run: |
        cd genx
        RELEASE_TAG=$(git describe --abbrev=0 --tags)
        python3 -c "from genx.version import increment_version;increment_version(minor=True, current='$RELEASE_TAG'.lstrip('v'))"
        GENX_VERSION=$(python -c "from genx.version import __version__;print('v'+__version__)")
        echo "GENX_VERSION=$GENX_VERSION" >> "$GITHUB_ENV"
    - name: Build html documentation
      run: |
        cd doc_source
        make html
    - name: Move files to doc location
      run: |
        rm -rf docs/doc/*
        mv doc_source/build/html/* docs/doc/
    - uses: stefanzweifel/git-auto-commit-action@v5
      name: Commit new documentation
      with:
        commit_message: Build documentation with Sphinx ${{ env.GENX_VERSION }}
        file_pattern: 'docs/doc/*'
        commit_user_email: artur.glavic@psi.ch
        commit_author: Artur Glavic <artur.glavic@psi.ch>
        #tagging_message: ${{ env.GENX_VERSION }}